force-app/main/default/mdapioutput/objects/Application__c.object
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{00000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Application_Stage__c</fullName>
        <label>Application Stage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Expression of Interest</fullName>
                    <default>true</default>
                    <label>Expression of Interest</label>
                </value>
                <value>
                    <fullName>Full Application</fullName>
                </value>
                <value>
                    <fullName>Live Project</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>application_theme__c</fullName>
        <label>Application Theme</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Children's services</fullName>
                </value>
                <value>
                    <fullName>Drug and alcohol dependency</fullName>
                </value>
                <value>
                    <fullName>Early years</fullName>
                </value>
                <value>
                    <fullName>Healthy lives</fullName>
                </value>
                <value>
                    <fullName>Older people's services</fullName>
                </value>
                <value>
                    <fullName>Young people</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Full_Application_Status__c</fullName>
        <label>Full Application Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Under review (In progress)</fullName>
                </value>
                <value>
                    <fullName>Ready for Approval</fullName>
                </value>
                <value>
                    <fullName>Successful</fullName>
                </value>
                <value>
                    <fullName>Unsuccessful</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/default/mdapioutput/objects/Form_LCF_Full_App_1__c.object
<CustomObject>
    <description>Life Chances Fund - Full Application - 1.0</description>
    <label>Form LCF Full Application 1.0</label>
    <nameField>
        <displayFormat>FAP-{00000}</displayFormat>
        <label>Form ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Form LCF Full Application 1.0</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Form LCF Full Application 1.0</relationshipLabel>
        <relationshipName>Form_LCF_Full_Application_1_0</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ov_services_start_date__c</fullName>
        <inlineHelpText>When would you like your project to start delivering services?</inlineHelpText>
        <label>OV - Services Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>si_themes__c</fullName>
        <inlineHelpText>What is the theme of your project?</inlineHelpText>
        <label>SI - Themes</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Children's services</fullName>
                </value>
                <value>
                    <fullName>Drug and alcohol dependency</fullName>
                </value>
                <value>
                    <fullName>Young people</fullName>
                </value>
                <value>
                    <fullName>Healthy lives</fullName>
                </value>
                <value>
                    <fullName>Older people's services</fullName>
                </value>
                <value>
                    <fullName>Early years</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/default/classes/COF_FullAppViewControllerTest.cls
/* _______________________________________________________________________________________________________________
   Name:		COF_FullAppViewControllerTest.cls
   Description: Test Class for COF_FullAppViewControlle
					
   Date         Version Author          	Summary of Changes 
   ___________  _______ __________________	______________________________________________________________________
   Mar 2018     1.0     Michael Witchalls	Initial Release 
__________________________________________________________________________________________________________________ */        
@isTest
private class COF_FullAppViewControllerTest { 
	private static final String RECORDTYPE = 'Full Application';
	private static final String THEME1 = 'Children\'s services';
	private static final String THEME2 = 'Healthy lives';
	private static final String STAGE = 'Full Application';
	private static final String DRAFT = 'Draft';
	
	@testSetup static void setup() {
    	
		// Create an Application
		Application__c a = new Application__c(
			RecordTypeId = Schema.SObjectType.Application__c.getRecordTypeInfosByName().get(RECORDTYPE).getRecordTypeId(),
			application_theme__c = THEME1,
			Application_Stage__c = STAGE,
			Full_Application_Status__c = DRAFT
		);
		insert a;
		// Create a Full Application Form
		Form_LCF_Full_App_1__c f = new Form_LCF_Full_App_1__c(
			application__c = a.Id,
			ov_services_start_date__c = System.Today(),
			si_themes__c = THEME1+';'+THEME2
		);
		insert f; 
	}    
	
    @isTest static void testit() {
    	Application__c a = [SELECT Id, Name FROM Application__c LIMIT 1];
    	Form_LCF_Full_App_1__c f = [SELECT Id, Name FROM Form_LCF_Full_App_1__c LIMIT 1];
		
        PageReference pageRef = Page.COF_FullAppViewOverride;
        Test.setCurrentPage(pageRef);     
        ApexPages.currentPage().getParameters().put('Id', f.Id);      
        
		Test.startTest();
		ApexPages.StandardController stdcon = new ApexPages.StandardController(f);
        COF_FullAppViewOverrideController con = new COF_FullAppViewOverrideController(stdcon);
        con.getViewAction();
        con.viewForm();
      	
     	Test.stopTest();
        system.assertEquals(a.Name, con.appId);
    }  
    
    
}