force-app/main/default/mdapioutput/objects/Application__c.object
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{00000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Application</relationshipLabel>
        <relationshipName>Application</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Full_Application_Status__c</fullName>
        <label>Full Application Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Under review (In progress)</fullName>
                </value>
                <value>
                    <fullName>Ready for Approval</fullName>
                </value>
                <value>
                    <fullName>Successful</fullName>
                </value>
                <value>
                    <fullName>Unsuccessful</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>EOI Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Under review (In progress)</fullName>
                </value>
                <value>
                    <fullName>Ready for Approval</fullName>
                </value>
                <value>
                    <fullName>Successful</fullName>
                </value>
                <value>
                    <fullName>Unsuccessful</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Theme__c</fullName>
        <formula>IF(NOT(ISBLANK(TEXT(application_theme__c))),
TEXT(application_theme__c),
Application_Window_Template__r.Application_Window__r.Theme__r.Name
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Theme</label>
        <type>Text</type>
    </fields>
</CustomObject>

force-app/main/default/objects/Application__c/fields/Full_App_Commissioner_Benefits__c.field-meta.xml
<CustomField>
    <fullName>Full_App_Commissioner_Benefits__c</fullName>
    <description>Full Application: maximum cashable benefits for commissioners of the project</description>
    <inlineHelpText>Full Application: maximum cashable benefits for commissioners of the project</inlineHelpText>
    <label>Full App Commissioner Benefits</label>
    <summarizedField>Form_LCF_Full_App_1__c.fn_max_benefits_commissioners__c</summarizedField>
    <summaryForeignKey>Form_LCF_Full_App_1__c.application__c</summaryForeignKey>
    <summaryOperation>max</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Full_App_Commissioner_Savings__c.field-meta.xml
<CustomField>
    <fullName>Full_App_Commissioner_Savings__c</fullName>
    <description>Full Application: maximum cashable savings for commissioners of the project</description>
    <inlineHelpText>Full Application: maximum cashable savings for commissioners of the project</inlineHelpText>
    <label>Full App Commissioner Savings</label>
    <summarizedField>Form_LCF_Full_App_1__c.fn_max_savings_commissioners__c</summarizedField>
    <summaryForeignKey>Form_LCF_Full_App_1__c.application__c</summaryForeignKey>
    <summaryOperation>max</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Full_App_LCF_Contribution__c.field-meta.xml
<CustomField>
    <fullName>Full_App_LCF_Contribution__c</fullName>
    <description>Full Application Maximum LCF Contribution</description>
    <inlineHelpText>Full Application Maximum LCF Contribution</inlineHelpText>
    <label>Full App LCF Contribution</label>
    <summarizedField>Form_LCF_Full_App_1__c.ov_max_requested_funds__c</summarizedField>
    <summaryForeignKey>Form_LCF_Full_App_1__c.application__c</summaryForeignKey>
    <summaryOperation>max</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Full_App_Other_Party_Benefits__c.field-meta.xml
<CustomField>
    <fullName>Full_App_Other_Party_Benefits__c</fullName>
    <description>Full application: maximum cashable benefits for other parties</description>
    <formula>Full_App_Total_Benefits__c -  Full_App_Commissioner_Benefits__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Full application: maximum cashable benefits for other parties</inlineHelpText>
    <label>Full App Other Party Benefits</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Full_App_Other_Party_Savings__c.field-meta.xml
<CustomField>
    <fullName>Full_App_Other_Party_Savings__c</fullName>
    <description>Full application: maximum cashable savings for other parties</description>
    <formula>Full_App_Total_Savings__c -  Full_App_Commissioner_Savings__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Full application: maximum cashable savings for other parties</inlineHelpText>
    <label>Full App Other Party Savings</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Full_App_Outcome_Payments__c.field-meta.xml
<CustomField>
    <fullName>Full_App_Outcome_Payments__c</fullName>
    <description>Full Application Maximum Outcome Payments</description>
    <inlineHelpText>Full Application Maximum Outcome Payments</inlineHelpText>
    <label>Full App Outcome Payments</label>
    <summarizedField>Form_LCF_Full_App_1__c.ov_max_estimated_outcomes_payments__c</summarizedField>
    <summaryForeignKey>Form_LCF_Full_App_1__c.application__c</summaryForeignKey>
    <summaryOperation>max</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Full_Award_Setup_Status__c.field-meta.xml
<CustomField>
    <fullName>Full_Award_Setup_Status__c</fullName>
    <label>Full Award Setup Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Under review (In progress)</fullName>
            </value>
            <value>
                <fullName>Ready for Approval</fullName>
            </value>
            <value>
                <fullName>Successful</fullName>
            </value>
            <value>
                <fullName>Unsuccessful</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/LCF_Grant__c/LCF_Grant__c.object-meta.xml
<CustomObject>
    <description>Life Changes Fund Grant Management master object</description>
    <label>LCF Grant</label>
    <nameField>
        <displayFormat>GNT-{00000}</displayFormat>
        <label>Grant ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LCF Grants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LCF_Grant__c/fields/ab_block_status__c.field-meta.xml
<CustomField>
    <fullName>ab_block_status__c</fullName>
    <description>Status of latest LCF grant achievement block</description>
    <inlineHelpText>Status of latest LCF grant achievement block</inlineHelpText>
    <label>Outcome Achievement Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Grant_Form_Block_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/LCF_Grant__c/fields/am_block_status__c.field-meta.xml
<CustomField>
    <fullName>am_block_status__c</fullName>
    <description>Status of latest annual monitoring block</description>
    <inlineHelpText>Status of latest annual monitoring block</inlineHelpText>
    <label>Annual Monitoring Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Grant_Form_Block_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/LCF_Grant__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>LCF Grants</relationshipLabel>
    <relationshipName>lcf_grants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LCF_Grant__c/fields/Application_ID__c.field-meta.xml
<CustomField>
    <fullName>Application_ID__c</fullName>
    <formula>Application__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Application ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LCF_Grant__c/fields/bb_block_status__c.field-meta.xml
<CustomField>
    <fullName>bb_block_status__c</fullName>
    <description>Status of offer letter baseline block</description>
    <inlineHelpText>Status of offer letter baseline block</inlineHelpText>
    <label>Baseline Block Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Grant_Form_Block_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/LCF_Grant__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Project Contact</description>
    <inlineHelpText>Project Contact</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>LCF Grants</relationshipLabel>
    <relationshipName>LCF_Grants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LCF_Grant__c/fields/pp_block_status__c.field-meta.xml
<CustomField>
    <fullName>pp_block_status__c</fullName>
    <description>Status of latest LCF payment profile block</description>
    <inlineHelpText>Status of latest LCF payment profile block</inlineHelpText>
    <label>Payment Profile Block Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Grant_Form_Block_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/LCF_Grant__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of project associated with SIB Grant</description>
    <inlineHelpText>Status of project associated with SIB Grant</inlineHelpText>
    <label>Grant Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>Award Issued</fullName>
            </value>
            <value>
                <fullName>Award Accepted</fullName>
            </value>
            <value>
                <fullName>Project Launched</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/LCF_Grant__c/fields/Theme__c.field-meta.xml
<CustomField>
    <fullName>Theme__c</fullName>
    <description>Theme of application project</description>
    <formula>Application__r.Theme__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Theme of application project</inlineHelpText>
    <label>Theme</label>
    <type>Text</type>
</CustomField>

force-app/main/default/mdapioutput/objects/Theme__c.object
<CustomObject>
    <description>The category under which projects are classified. Applicants interest is initially captured against a theme</description>
    <label>Theme</label>
    <nameField>
        <label>Theme Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Themes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Grant_Form_Block_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>NOT STARTED</fullName>
        <default>true</default>
        <label>NOT STARTED</label>
    </customValue>
    <customValue>
        <fullName>IN PROGRESS</fullName>
    </customValue>
    <customValue>
        <fullName>COMPLETE</fullName>
    </customValue>
    <customValue>
        <fullName>HISTORY</fullName>
    </customValue>
    <description>Status of Grant Form Block</description>
    <masterLabel>Grant Form Block Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/COF_PageController.cls
/**
 * COF_PageController
 * Cabinet Office Forms 1.0
 *
 * This abstract class is inherited by each Page Controller.
 */
public virtual class COF_PageController {
	private static final String CONTENTDOCURL = '/communityprefix/sfc/servlet.shepherd/version/download';
	private static final String EOISTATUS = 'Status__c';
	private static final String FULLAPPSTATUS = 'Full_Application_Status__c';
	private static final String SETUPSTATUS = 'Full_Award_Setup_Status__c';
	private static final String DRAFT = 'DRAFT';
	private static final String NOTSTARTED = 'NOT STARTED';
	private static final String SUBMITTED = 'Submitted';
	private static final String APPROVED = 'Approved';
	private static final String ISSUED = 'Issued';
    private static final String PARTNERUSERTYPE = 'PowerPartner';
    private static final String CUSTOMERUSERTYPE = 'PowerCustomerSuccess';
    private static final List<String> FINANCEFIELDS = new List<String>{
    	'Full_App_Commissioner_Savings__c',
    	'Full_App_Commissioner_Benefits__c',
    	'Full_App_Other_Party_Savings__c',
    	'Full_App_Other_Party_Benefits__c',
    	'Full_App_Outcome_Payments__c',
    	'Full_App_LCF_Contribution__c'
    };
    private static final String PROJECT = 'PROJECT';
    private static final String FUNDING = 'FUNDING';
    private static final List<String> BLOCKSTATUSFIELDS = new List<String>{
    	'bb_block_status__c',
    	'ab_block_status__c',
    	'pp_block_status__c',
    	'am_block_status__c'
    };
    private String userType; 
    private String communityURLPrefix;
    
    public String getContentURL() {
    	if (this.getCommunityPrefix() != null) {
    		return CONTENTDOCURL.replace('communityprefix', this.getCommunityPrefix());
    	} else {
    		return CONTENTDOCURL.replace('communityprefix/','');
    	}
    }
    
    public String getCommunityPrefix() {
    	if (this.getCustomerUser() || this.getPartnerUser()) {
	    	if (this.communityURLPrefix == null) {
	    		this.communityURLPrefix = [SELECT Network.UrlPathPrefix FROM NetworkMember WHERE MemberId = :UserInfo.getUserId()].Network.UrlPathPrefix;
	    	}
	    	//system.assert(false, communityURLPrefix);
	    	return communityURLPrefix;
    	} else {
    		return null;
    	}
    }

	public Boolean getPartnerUser() {
		if (this.userType == null) {
    		this.userType = [SELECT UserType FROM User WHERE Id = :UserInfo.getUserId()].UserType;
		}
    	return (userType == PARTNERUSERTYPE);	
	}

	public Boolean getCustomerUser() {
		if (this.userType == null) {
    		this.userType = [SELECT UserType FROM User WHERE Id = :UserInfo.getUserId()].UserType;
		}
		system.debug('@@@@@userType: '+userType+' '+(userType==CUSTOMERUSERTYPE));
    	return (userType == CUSTOMERUSERTYPE);	
	}
	
	public String getPageName() {
		return ApexPages.currentPage().getUrl().substringAfterLast('/').substringBefore('?');
	}
    
    //As with all the pages where we require a user to be logged in, we check here if the user is logged in, else return the homepage
    public PageReference checkLoggedInStatus(){
    	return SIB_Utilities.checkLoggedInStatus();
    }
    
    // M.Witchalls Apr 2018: for readonly view (if application form not in 'Draft' status, or for grant forms, not submitted for approval or approved)        
   	public Boolean getReadOnlyMode(SObject application, COF_Form form, SObject grantObject) {
   		return getReadOnlyMode(application, form, grantObject, null);
   	}
   	
   	public Boolean getReadOnlyMode(SObject application, COF_Form form, SObject grantObject, String parentRelationship) {
        String grantIdentifier = this.getGrantIdentifierParam();
   		if (String.isBlank(grantIdentifier)) {
   			return getAppReadOnlyMode(application, form);
   		} else {
   			return getGrantReadOnlyMode(grantObject, form, parentRelationship);
   		}
   	}
   	
    public Boolean getAppReadOnlyMode(SObject application, COF_Form form) {
		return (this.getFormStatus(application, form)!= DRAFT);
    } 
   	
    public Boolean getGrantReadOnlyMode(SObject grantObject, COF_Form form, String parentRelationship) {
    	String editUsers = form.users_able_to_edit;
		if (editUsers != null) {
			editUsers = editUsers.toUpperCase();
	   		if (this.getCustomerUser() && !editUsers.contains(PROJECT)) {
	   			return true;
	   		} else if (this.getPartnerUser() && !editUsers.contains(FUNDING)) {
	   			return true;
			}
   		}   		
		if (grantObject != null) {
			String status;
			system.debug('@@@@parentRelationship: '+parentRelationship);
			if (parentRelationship != null) {
				if (form.issue_status_field != null) { 
					status = (String)grantObject.getSObject(parentRelationship).get(form.issue_status_field);
				} else {
					status = (String)grantObject.getSObject(parentRelationship).get(form.approval_status_field);
				}
			} else {
				if (form.issue_status_field != null) { 
		        	status = (String)grantObject.get(form.issue_status_field);
				} else {
		        	status = (String)grantObject.get(form.approval_status_field);
				}
			}
	    	return (status == SUBMITTED || status == APPROVED || status == ISSUED);
		} else {
			return false;
		}
    } 

    public virtual String getFormStatus(SObject record, COF_Form form) {
    	String status;
    	if (record.getSObjectType() == Application__c.sObjectType) {
	    	status = (String)record.get(form.application_status_field);
	    	if (status == null) status = DRAFT;
    	} else if (record.getSObjectType() == LCF_Grant__c.sObjectType) {
	    	status = (String)record.get(form.block_status_field);
	    	if (status == null) status = NOTSTARTED;    		
    	}
    	return status.toUpperCase(); 
    }

	/**
	 * Returns the application object based on the reference given in the "app" URL parameter
	 */
	public virtual SObject getApplication() {
        List<String> fields = new List<String>();
        fields.add('Name');
        fields.add('Theme__c');
        fields.add(EOISTATUS);
        fields.add(FULLAPPSTATUS);
        fields.add(SETUPSTATUS);
        fields.add('Contact__r.Name');
        fields.addAll(FINANCEFIELDS);
        
        String applicationIdentifier = this.getApplicationIdentifierParam();
        String grantIdentifier = this.getGrantIdentifierParam();
        if (!String.isBlank(applicationIdentifier)) {
        	return Query.object('Application__c', fields, 'WHERE Name = \'' + applicationIdentifier + '\'');
        } else if (!String.isBlank(grantIdentifier)) {
        	return Query.object('Application__c', fields, 'WHERE Id IN (SELECT Application__c FROM LCF_Grant__c WHERE Name = \'' + grantIdentifier + '\')');
        } else {
        	return null;
        }
        // Query class will throw exception if no matches
	}

	/**
	 * Returns the grant object based on the reference given in the "grant" URL parameter
	 */
	public virtual SObject getGrant() {
		String grantIdentifier = this.getGrantIdentifierParam();
		if (!String.isBlank(grantIdentifier)) {
	        List<String> fields = new List<String>();
	        fields.add('Name');
	        fields.add('Theme__c');
	        fields.add('Status__c');
	        fields.add('Application__c');
	        fields.add('Application_ID__c');
	        fields.addAll(BLOCKSTATUSFIELDS);
	        fields.add('Contact__r.Name');
	        fields.add('OwnerId');
	        return Query.object('LCF_Grant__c', fields, 'WHERE Name = \'' + grantIdentifier + '\'');
	        // Query class will throw exception if no matches
		} else {
			return null;
		}
	}

	/**
	 * Returns the application identifier parameter value
	 */
	public virtual String getApplicationIdentifierParam() {
		return this.getPageParam('app');
	}

	/**
	 * Returns the grant identifier parameter value
	 */
	public virtual String getGrantIdentifierParam() {
		return this.getPageParam('grant');
	}

	/**
	 * Returns the record identifier parameter value
	 */
	public virtual String getRecordIdentifierParam() {
		return this.getPageParam('id');
	}

	/**
	 * Returns the form identifier parameter value
	 */
	public virtual String getFormIdentifierParam() {
		return this.getPageParam('form');
	}

	/**
	 * Returns the section identifier parameter value
	 */
	public virtual String getSectionIdentifierParam() {
		return this.getPageParam('section');
	}

	/**
	 * Returns the page identifier parameter value
	 */
	public virtual String getPageIdentifierParam() {
		return this.getPageParam('page');
	}

	/**
	 * Returns the previous page identifier parameter value
	 */
	public virtual String getPreviousPageIdentifierParam() {
		return this.getPageParam('previousPage');
	}

	/**
	 * Returns the fromForm identifier parameter value
	 */
	public virtual String getFromFormIdentifierParam() {
		return this.getPageParam('fromForm');
	}

	/**
	 * Returns a page URL parameter given an identifier
	 */
	public virtual String getPageParam(String identifier) {
		String param = ApexPages.currentPage().getParameters().get(identifier);
		if (param != null)
			return param;
		return null;
	}

	/**
	 * Determines whether the current user has successfully logged in 
	 */
	public Boolean isAuthorisedUser() {
		return true;
	}
}