force-app/main/default/mdapioutput/objects/Application_Question__c.object
<CustomObject>
    <label>Application Question</label>
    <nameField>
        <label>Application Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Question</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Field_From_Contact_Record__c</fullName>
        <description>This is the API name of the field on the contact record you wish to pull the value from.</description>
        <inlineHelpText>This is the API name of the field on the contact record you wish to pull the value from.</inlineHelpText>
        <label>Field From Contact Record</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field_To_Set_On_Answer__c</fullName>
        <label>Field To Set On Answer</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Short_Text_Answer__c</fullName>
                </value>
                <value>
                    <fullName>Checkbox_Answer__c</fullName>
                </value>
                <value>
                    <fullName>Checkboxes_Answer__c</fullName>
                </value>
                <value>
                    <fullName>Date_Answer__c</fullName>
                </value>
                <value>
                    <fullName>Email_Answer__c</fullName>
                </value>
                <value>
                    <fullName>Multi_Picklist_Answers__c</fullName>
                </value>
                <value>
                    <fullName>Percent_Answer__c</fullName>
                </value>
                <value>
                    <fullName>Picklist_Answer__c</fullName>
                </value>
                <value>
                    <fullName>Text_Answer__c</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Help_Text__c</fullName>
        <label>Help Text</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
</CustomObject>

force-app/main/default/mdapioutput/objects/Application_Question_Template__c.object
<CustomObject>
    <label>Application Question Template</label>
    <nameField>
        <displayFormat>AQT-{00000}</displayFormat>
        <label>Application Question Template Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Question Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Application_Question__c</fullName>
        <label>Application Question</label>
        <referenceTo>Application_Question__c</referenceTo>
        <relationshipName>Question_Templates</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Application_Window_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application Window Template</label>
        <referenceTo>Application_Window_Template__c</referenceTo>
        <relationshipLabel>Application Question Templates</relationshipLabel>
        <relationshipName>Question_Templates</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

force-app/main/default/mdapioutput/objects/Application_Window_Template__c.object
<CustomObject>
    <label>Application Window Template</label>
    <nameField>
        <displayFormat>AWT-{0}</displayFormat>
        <label>Iteration Template Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Window Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SIB_Field_Metadata__c/SIB_Field_Metadata__c.object-meta.xml
<CustomObject>
    <description>Life Chances Fund - Field metadata extracted via Metadata API and updated with custom attributes</description>
    <label>SIB Field Metadata</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SIB Field Metadata</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SIB_Field_Metadata__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Field Description (Guidance)</description>
    <inlineHelpText>Field Description (Guidance)</inlineHelpText>
    <label>Description (Guidance)</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SIB_Field_Metadata__c/fields/Field_Key__c.field-meta.xml
<CustomField>
    <fullName>Field_Key__c</fullName>
    <description>ObjectName.FieldName</description>
    <externalId>true</externalId>
    <inlineHelpText>ObjectName.FieldName</inlineHelpText>
    <label>Field Key</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SIB_Field_Metadata__c/fields/Help_Text__c.field-meta.xml
<CustomField>
    <fullName>Help_Text__c</fullName>
    <description>Field Help Text (Form Question Label)</description>
    <inlineHelpText>Field Help Text (Form Question Label)</inlineHelpText>
    <label>Help Text (Question Label)</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SIB_Field_Metadata__c/fields/Page_Title__c.field-meta.xml
<CustomField>
    <fullName>Page_Title__c</fullName>
    <description>Title of form page where field appears</description>
    <inlineHelpText>Title of form page where field appears</inlineHelpText>
    <label>Page Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SIB_Field_Metadata__c/fields/Recommended_Word_Limit__c.field-meta.xml
<CustomField>
    <fullName>Recommended_Word_Limit__c</fullName>
    <description>Recommended word limit for textarea fields</description>
    <inlineHelpText>Recommended word limit for textarea fields</inlineHelpText>
    <label>Recommended Word Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SIB_Field_Metadata__c/fields/Relationship_Name__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Name__c</fullName>
    <description>Child Relationship Query Name</description>
    <inlineHelpText>Child Relationship Query Name</inlineHelpText>
    <label>Child Relationship Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SIB_Field_Metadata__c/fields/Rich_Text__c.field-meta.xml
<CustomField>
    <fullName>Rich_Text__c</fullName>
    <description>Form Field Rich Text (additional or an alternative to Guidance)</description>
    <inlineHelpText>Form Field Rich Text (additional or an alternative to Guidance)</inlineHelpText>
    <label>Rich Text (Guidance)</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/SIB_Field_Metadata__c/fields/Warning_Text__c.field-meta.xml
<CustomField>
    <fullName>Warning_Text__c</fullName>
    <description>Warning text to trigger email to applicant</description>
    <inlineHelpText>Warning text to trigger email to applicant</inlineHelpText>
    <label>Warning Text</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SIB_Field_Metadata__c/fields/Warning_Value__c.field-meta.xml
<CustomField>
    <fullName>Warning_Value__c</fullName>
    <description>Field value that triggers the Warning Text</description>
    <inlineHelpText>Field value that triggers the Warning Text</inlineHelpText>
    <label>Warning Value</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SIB_Section_Text__c/SIB_Section_Text__c.object-meta.xml
<CustomObject>
    <description>Rich text used in Section Titles in SIB Forms</description>
    <label>SIB Section Text</label>
    <nameField>
        <label>Text ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SIB Section Text</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SIB_Section_Text__c/fields/Key__c.field-meta.xml
<CustomField>
    <fullName>Key__c</fullName>
    <description>Object Name:Text ID</description>
    <externalId>true</externalId>
    <inlineHelpText>This field is populated automatically by Salesforce workflow and should  be cleared when cloning</inlineHelpText>
    <label>Key</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/SIB_Utilities.cls
/* __________________________________________________________________________________________________________________
   Name:		SIB_Utilities.cls
   Description: General Utility Class
					
   Date         Version Author          		Summary of Changes 
   ___________  _______ __________________		_____________________________________________________________________
   2017		    1.0    	Cabinet Office			Initial Release 
   Feb 2018		1.1		M.Witchalls, Westbrook	Extraction of field metadata and section text
__________________________________________________________________________________________________________________ */        
public class SIB_Utilities {
	public static Map<String, Map<String, Id>> recordTypeIdCache = new Map<String, Map<String, Id>>();
	public static Map<String, SIB_Field_Metadata__c> fieldMetadataCache = new Map<String, SIB_Field_Metadata__c>();
	public static Map<String, SIB_Section_Text__c> sectionTextCache = new Map<String, SIB_Section_Text__c>();

	/*
		Utility method to query LCF field descriptions.
		LCF field descriptions and other metadata are extracted by a Visualforce Page button via the Metadata API 
		and stored in the custom object SIB_Field_Metadata__c so as to be available to end users.
		
		M.Witchalls Feb 2018		
	*/
	public static SIB_Field_Metadata__c getFieldMetadata(String objectName, String fieldName) {
		String fieldKey = objectName+'.'+fieldName;
		if(fieldMetadataCache.size() == 0 && !Test.isRunningTest()) {
			fieldMetadataCache = new Map<String, SIB_Field_Metadata__c>();
			for (List<SIB_Field_Metadata__c> fdList: [
				SELECT 
					Name, Field_Key__c, Description__c, Help_Text__c, Relationship_Name__c,
					Rich_Text__c, Recommended_Word_Limit__c, Warning_Text__c, Warning_Value__c, Page_Title__c 
				FROM 
					SIB_Field_Metadata__c
			]) {
				for (SIB_Field_Metadata__c fm: fdList) {
					fieldMetadataCache.put(fm.Field_Key__c, fm);
				} 
			}
		}
		return fieldMetadataCache.get(fieldKey);
	}

	/*
		Utility method to extract rich text for LCF sections.
		LCF section text is stored in the SIB Section Text object and accessed via title_id, guidance_id, warning_id etc
		
		M.Witchalls Feb 2018		
	*/
	public static SIB_Section_Text__c getSectionText(String textKey) {
		return SIB_Utilities.getSectionText(textKey, false);
	}
	public static SIB_Section_Text__c getSectionText(String textKey, Boolean ignoreNulls) { 
		SIB_Section_Text__c returnObject;
		if (sectionTextCache.size() == 0) {
			sectionTextCache = new Map<String, SIB_Section_Text__c>();
			
	        SIB_TemplateController con = new SIB_TemplateController();
	        for (SIB_Section_Text__c st: con.sibInfo.Section_Text__r) {
	        	sectionTextCache.put(st.Key__c, st);
	        } 
		}
		returnObject = sectionTextCache.get(textKey);
		if (returnObject == null) {
			if (ignoreNulls) return null;
			throw new COF_Exception('Could not find custom text with key: '+textKey);
		}
		return returnObject;
	}

	/*
		This method will be used in SIB_SelfRegController and SIB_ApplicationFormExtension. 
		Using this method here will allow one regex in multiple places and will give an easier way to maintain this.
	*/
	public static Boolean isValidEmail(String email) {
		String emailRegex = '^[a-zA-Z0-9\\.\\!\\#\\$\\%\\&\\*\\/\\=\\?\\^\\_\\+\\-\\`\\{\\|\\}\\~\'._%+-]+@[a-zA-Z0-9\\-.-]+\\.[a-zA-Z]+';
		Pattern myPattern = Pattern.compile(emailRegex);
		Matcher myMatcher = myPattern.matcher(email);
		return myMatcher.matches();
	}

	/*
		This method retrieves all questions where there is a "Field From Contact Record" value populated and returns these in
		a string to be used in a query.
	*/
	public static String generateDefaultFields(Id applicationWindowTemplateId){
		String fieldsToReturn = '';
		for(Application_Question_Template__c singleQuestionTemplate : [
			SELECT Application_Question__r.Field_From_Contact_Record__c, Application_Question__r.Field_To_Set_On_Answer__c
			FROM Application_Question_Template__c
			WHERE Application_Window_Template__r.Id = :applicationWindowTemplateId
			AND Application_Question__r.Field_From_Contact_Record__c != null
			ORDER BY CreatedDate ASC
		]){
			fieldsToReturn += singleQuestionTemplate.Application_Question__r.Field_From_Contact_Record__c + ',';
		}
		fieldsToReturn += 'Id';
		return fieldsToReturn;
	}

	/*
		Utility method to query record type Id's. It stores all record types for a particular object to store them for later use,
		which allows a more effective use than querying the record type each time.
	*/
	public static Id getRecordTypeId(String objName, String rtName) {
		if(!recordTypeIdCache.containsKey(objName)){
			Map<String, Id> valuesToPut = new Map<String, Id>();
			Map<String,Schema.RecordTypeInfo> recordTypeInfo = Schema.getGlobalDescribe().get(objName).getDescribe().getRecordTypeInfosByName();
			for(String recordTypeInfoName : recordTypeInfo.keySet()){
				valuesToPut.put(recordTypeInfoName, recordTypeInfo.get(recordTypeInfoName).getRecordTypeId());
			}
			recordTypeIdCache.put(objName, valuesToPut);
		}
		return recordTypeIdCache.get(objName).get(rtName);
	}

	/*
		This method is used on every page to check if the user is logged in, therefore shielding these pages from external views.
		We need to check that the is no user AND that the user is not the community user.
	*/
	public static PageReference checkLoggedInStatus(){
		PageReference pageReferenceToReturn = 
		UserInfo.getUserId() == null || UserInfo.getUserName().startsWith('social_impact_bonds@') ? 
			returnHomePage() : 
			null;
        return pageReferenceToReturn;
	}   

	/*
		Single method to return the base URL of the site. This can be used in multiple places and allows easier upkeep.
	*/
	public static PageReference returnHomePage(){
		return Page.SIB_Login;
	}
}