force-app/main/default/mdapioutput/objects/Application_Form_Section__c.object
<CustomObject>
    <description>This will hold the help text to allow us to display the user the overview screen.</description>
    <label>Application Form Section</label>
    <nameField>
        <label>Application Form Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Form Sections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/mdapioutput/objects/Application_Question__c.object
<CustomObject>
    <label>Application Question</label>
    <nameField>
        <label>Application Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Question</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/mdapioutput/objects/Application_Question_Template__c.object
<CustomObject>
    <label>Application Question Template</label>
    <nameField>
        <displayFormat>AQT-{00000}</displayFormat>
        <label>Application Question Template Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Question Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Application_Form_Section__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Application Form Section</label>
        <referenceTo>Application_Form_Section__c</referenceTo>
        <relationshipLabel>Application Question Templates</relationshipLabel>
        <relationshipName>Application_Question_Templates</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Application_Question__c</fullName>
        <label>Application Question</label>
        <referenceTo>Application_Question__c</referenceTo>
        <relationshipName>Question_Templates</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Application_Window_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application Window Template</label>
        <referenceTo>Application_Window_Template__c</referenceTo>
        <relationshipLabel>Application Question Templates</relationshipLabel>
        <relationshipName>Question_Templates</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

force-app/main/default/mdapioutput/objects/Application_Window__c.object
<CustomObject>
    <description>Controls whether a theme is accepting applications</description>
    <label>Application Window</label>
    <nameField>
        <label>Application Window Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Windows</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Theme__c</fullName>
        <label>Theme</label>
        <referenceTo>Theme__c</referenceTo>
        <relationshipLabel>Application Windows</relationshipLabel>
        <relationshipName>Application_Windows</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

force-app/main/default/mdapioutput/objects/Application_Window_Template__c.object
<CustomObject>
    <label>Application Window Template</label>
    <nameField>
        <displayFormat>AWT-{0}</displayFormat>
        <label>Iteration Template Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Window Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Application_Window__c</fullName>
        <label>Application Window</label>
        <referenceTo>Application_Window__c</referenceTo>
        <relationshipLabel>Application Window Templates</relationshipLabel>
        <relationshipName>Application_Window_Templates</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Theme__c</fullName>
        <formula>Application_Window__r.Theme__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Theme</label>
        <type>Text</type>
    </fields>
</CustomObject>

force-app/main/default/mdapioutput/objects/Theme__c.object
<CustomObject>
    <description>The category under which projects are classified. Applicants interest is initially captured against a theme</description>
    <label>Theme</label>
    <nameField>
        <label>Theme Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Themes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/SIB_UtilitiesTest.cls
@isTest
private class SIB_UtilitiesTest {
	
	@testSetup static void initData(){
		Theme__c theme = DataFactory.insertTheme('Test Theme');
		Application_Window__c aw = DataFactory.insertAW(theme.Id);
		Application_Window_Template__c awt = DataFactory.insertAWT(aw.Id);
		Application_Form_Section__c afs = DataFactory.insertAFS('Test Section', 'Expression of Interest');
		Application_Question__c aq = DataFactory.insertAQ('First Name', 'Short Text', 'FirstName', 'Short_Text_Answer__c', '', '1');
		Application_Question_Template__c aqt = DataFactory.insertAQT(awt.Id, aq.Id, afs.Id);
	}

	static testMethod void positiveTesting() {
		System.assertEquals(false, SIB_Utilities.isValidEmail('test@'));
		System.assertEquals(false, SIB_Utilities.isValidEmail('test@test'));
		System.assertEquals(true, SIB_Utilities.isValidEmail('test@test.com'));
		System.assertNotEquals(null, SIB_Utilities.getRecordTypeId('Contact', 'Customer User'));
		System.assertEquals(Page.SIB_Login.getURL(), SIB_Utilities.returnHomePage().getURL());
		System.assertEquals('Id', SIB_Utilities.generateDefaultFields(null));
		System.assertEquals(null, SIB_Utilities.checkLoggedInStatus());
		Application_Window_Template__c awt = [
			SELECT Id
			FROM Application_Window_Template__c
			LIMIT 1
		];
		System.assertEquals('FirstName,Id', SIB_Utilities.generateDefaultFields(awt.Id));
        SIB_Utilities.returnHomePage();
	}
}