force-app/main/default/mdapioutput/objects/Application__c.object
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{00000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Application_Stage__c</fullName>
        <label>Application Stage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Expression of Interest</fullName>
                    <default>true</default>
                    <label>Expression of Interest</label>
                </value>
                <value>
                    <fullName>Full Application</fullName>
                </value>
                <value>
                    <fullName>Live Project</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>application_theme__c</fullName>
        <label>Application Theme</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Children's services</fullName>
                </value>
                <value>
                    <fullName>Drug and alcohol dependency</fullName>
                </value>
                <value>
                    <fullName>Early years</fullName>
                </value>
                <value>
                    <fullName>Healthy lives</fullName>
                </value>
                <value>
                    <fullName>Older people's services</fullName>
                </value>
                <value>
                    <fullName>Young people</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Full_Application_Status__c</fullName>
        <label>Full Application Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Under review (In progress)</fullName>
                </value>
                <value>
                    <fullName>Ready for Approval</fullName>
                </value>
                <value>
                    <fullName>Successful</fullName>
                </value>
                <value>
                    <fullName>Unsuccessful</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/default/mdapioutput/objects/Form_LCF_Full_App_1__c.object
<CustomObject>
    <description>Life Chances Fund - Full Application - 1.0</description>
    <label>Form LCF Full Application 1.0</label>
    <nameField>
        <displayFormat>FAP-{00000}</displayFormat>
        <label>Form ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Form LCF Full Application 1.0</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Form LCF Full Application 1.0</relationshipLabel>
        <relationshipName>Form_LCF_Full_Application_1_0</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ov_section_status__c</fullName>
        <inlineHelpText>Overview section status</inlineHelpText>
        <label>OV - Section Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Form_Section_Status</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/default/globalValueSets/Form_Section_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>INCOMPLETE</fullName>
        <default>true</default>
        <label>INCOMPLETE</label>
    </customValue>
    <customValue>
        <fullName>COMPLETE</fullName>
    </customValue>
    <description>Status values for SIB Form Sections</description>
    <masterLabel>Form Section Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SectionsControllerTest.cls
/* _______________________________________________________________________________________________________________
   Name:		SectionsControllerTest.cls
   Description: Test Class for SectionsController
					
   Date         Version Author          	Summary of Changes 
   ___________  _______ __________________	______________________________________________________________________
   Jan 2018     1.0     Michael Witchalls	Initial Release 
__________________________________________________________________________________________________________________ */        
@isTest
private class SectionsControllerTest { 
	private static final String RECORDTYPE = 'Full Application';
	private static final String THEME1 = 'Children\'s services';
	private static final String THEME2 = 'Healthy lives';
	private static final String STAGE = 'Full Application';
	private static final String DRAFT = 'Draft';
	private static final String SUBMITTED = 'Submitted';
	private static final String INCOMPLETE = 'INCOMPLETE';
	
	@testSetup static void setup() {
    	
		// Create an Application
		Application__c a = new Application__c(
			RecordTypeId = Schema.SObjectType.Application__c.getRecordTypeInfosByName().get(RECORDTYPE).getRecordTypeId(),
			application_theme__c = THEME1,
			Application_Stage__c = STAGE,
			Full_Application_Status__c = DRAFT
		);
		insert a;
	}    
	
    @isTest static void testit() {
    	// Sections?form=lcf_full_app_1&app=APP-01118
    	Application__c a = [SELECT Id, Name FROM Application__c LIMIT 1];
		
        PageReference pageRef = Page.Sections;
        Test.setCurrentPage(pageRef);     
        ApexPages.currentPage().getParameters().put('app', a.Name);      
        ApexPages.currentPage().getParameters().put('form', 'lcf_full_app_1');      
         
		Test.startTest();
		SectionsController con1 = new SectionsController();
		con1.initialAction();
		con1.submit();
		con1.viewAll();
     	
     	Test.stopTest();
    	a = [SELECT Id, Name, Full_Application_Status__c FROM Application__c LIMIT 1];
     	Form_LCF_Full_App_1__c f = [SELECT Id, Name, ov_section_status__c FROM Form_LCF_Full_App_1__c LIMIT 1];
     	
        system.assertEquals(INCOMPLETE, f.ov_section_status__c);
		system.assertEquals(SUBMITTED, a.Full_Application_Status__c);
    }  
    
    
}