force-app/main/default/mdapioutput/objects/Application__c.object
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{00000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Reviewer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reviewer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Application</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

force-app/main/default/objects/Form_LCF_Setup_1__c/Form_LCF_Setup_1__c.object-meta.xml
<CustomObject>
    <description>Life Chances Fund - Full Award Set-Up Form - 1.0</description>
    <label>Form LCF Full Award Setup 1.0</label>
    <nameField>
        <displayFormat>STP-{00000}</displayFormat>
        <label>Form ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Form LCF Full Award Setup 1.0</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Form_LCF_Setup_1__c/fields/application__c.field-meta.xml
<CustomField>
    <fullName>application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Form LCF Full Award Setup 1.0</relationshipLabel>
    <relationshipName>Form_LCF_Full_Award_Setup_1_0</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/COF_SetupViewOverrideController.cls
/* _______________________________________________________________________________________________________________________
   Name:        COF_SetupViewOverrideController.cls
   Description: Extension controller class for COF_SetupViewOverride page (detail view override for Partner Users)
   				and COF_SetupFormView page (direct access to form)
					
   Date         Version Author          	Summary of Changes 
   ___________  _______ __________________	______________________________________________________________________________
   Mar 2018     1.0     Michael Witchalls	Initial Release 
________________________________________________________________________________________________________________________ */        
public without sharing class COF_SetupViewOverrideController {
    private String FORM = 'lcf_setup_1';
    private String PARTNERUSER = 'PowerPartner';
    public String appId;
    private String idString;
    private String userType; 
    private ApexPages.StandardController stdCon;
	     
    public COF_SetupViewOverrideController(ApexPages.StandardController stdController) { 
    	this.stdCon = stdController;
		this.idString = ApexPages.currentPage().getParameters().get('id');   		
    	List<Form_LCF_Setup_1__c> forms = [SELECT Application__r.Name FROM Form_LCF_Setup_1__c WHERE Id = :this.idString];
    	if (forms.size() > 0) {
    		this.appId = forms[0].Application__r.Name;
    		system.debug('@@@@this.appId: '+this.appId);
    	}
    	this.userType = [SELECT UserType FROM User WHERE Id = :UserInfo.getUserId()].UserType;
    }

    public PageReference getViewAction() {
    	if (this.userType != PARTNERUSER) {
    		PageReference nextPage = this.stdCon.view();
    		nextPage.getParameters().put('nooverride', '1');
	        nextPage.setRedirect(true);
	        return nextPage;
    	} else {
	        return viewForm();
    	}
	}

    public PageReference viewForm() {
    	PageReference nextPage = Page.Sections;
	    nextPage.getParameters().put('app', this.appId);
	    nextPage.getParameters().put('form', this.FORM);
        nextPage.setRedirect(true);
        return nextPage;
   }
}