force-app/main/default/mdapioutput/objects/Application__c.object
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{00000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Application_Stage__c</fullName>
        <label>Application Stage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Expression of Interest</fullName>
                    <default>true</default>
                    <label>Expression of Interest</label>
                </value>
                <value>
                    <fullName>Full Application</fullName>
                </value>
                <value>
                    <fullName>Live Project</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>application_theme__c</fullName>
        <label>Application Theme</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Children's services</fullName>
                </value>
                <value>
                    <fullName>Drug and alcohol dependency</fullName>
                </value>
                <value>
                    <fullName>Early years</fullName>
                </value>
                <value>
                    <fullName>Healthy lives</fullName>
                </value>
                <value>
                    <fullName>Older people's services</fullName>
                </value>
                <value>
                    <fullName>Young people</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Organisation_Name__c</fullName>
        <formula>Contact__r.Account.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Organisation Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>EOI Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Under review (In progress)</fullName>
                </value>
                <value>
                    <fullName>Ready for Approval</fullName>
                </value>
                <value>
                    <fullName>Successful</fullName>
                </value>
                <value>
                    <fullName>Unsuccessful</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/default/objects/Application_Answer__c/Application_Answer__c.object-meta.xml
<CustomObject>
    <description>Captures applicants responses to questions in the expression of interest form</description>
    <label>Application Answer</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Application Answers Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Answer</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Application_Answer__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Application Answer</relationshipLabel>
    <relationshipName>Application_Answer_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application_Answer__c/fields/Application_Question__c.field-meta.xml
<CustomField>
    <fullName>Application_Question__c</fullName>
    <label>Application Question</label>
    <referenceTo>Application_Question__c</referenceTo>
    <relationshipLabel>Application Answer</relationshipLabel>
    <relationshipName>Application_Answer</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Application_Answer__c/fields/Currency_Answer__c.field-meta.xml
<CustomField>
    <fullName>Currency_Answer__c</fullName>
    <defaultValue>null</defaultValue>
    <label>Currency Answer</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Application_Answer__c/fields/Data_Conversion_Form__c.field-meta.xml
<CustomField>
    <fullName>Data_Conversion_Form__c</fullName>
    <label>Data Conversion Form</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application_Answer__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <formula>Application_Question__r.Question__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Question</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application_Answer__c/fields/Short_Text_Answer__c.field-meta.xml
<CustomField>
    <fullName>Short_Text_Answer__c</fullName>
    <label>Short Text Answer</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application_Commissioner__c/Application_Commissioner__c.object-meta.xml
<CustomObject>
    <description>This will be a junction object between commissioner and application and will allow one commissioner to be added to multiple applications (saves too many contact records being created).</description>
    <label>Application Commissioner</label>
    <nameField>
        <label>Application Commisioner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Commissioners</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Application_Commissioner__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <description>This is the application the commissioner is related to.</description>
    <inlineHelpText>This is the application the commissioner is related to.</inlineHelpText>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Application Commissioners</relationshipLabel>
    <relationshipName>Application_Commissioners</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/mdapioutput/objects/Application_Question__c.object
<CustomObject>
    <label>Application Question</label>
    <nameField>
        <label>Application Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Question</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Help_Text__c</fullName>
        <label>Help Text</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Question_Number__c</fullName>
        <externalId>true</externalId>
        <label>Question ID</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Question_Type__c</fullName>
        <label>Question Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Short Text</fullName>
                </value>
                <value>
                    <fullName>Long Text</fullName>
                </value>
                <value>
                    <fullName>Date</fullName>
                </value>
                <value>
                    <fullName>Single Picklist</fullName>
                </value>
                <value>
                    <fullName>Multi-Select Picklist</fullName>
                </value>
                <value>
                    <fullName>Checkbox</fullName>
                </value>
                <value>
                    <fullName>Checkboxes</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Phone</fullName>
                </value>
                <value>
                    <fullName>Number</fullName>
                </value>
                <value>
                    <fullName>Currency</fullName>
                </value>
                <value>
                    <fullName>Percent</fullName>
                </value>
                <value>
                    <fullName>Radio Select</fullName>
                </value>
                <value>
                    <fullName>Single Checkbox</fullName>
                </value>
                <value>
                    <fullName>Attachment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <label>Question</label>
        <type>TextArea</type>
    </fields>
</CustomObject>

force-app/main/default/objects/Form_LCF_EOI_1__c/Form_LCF_EOI_1__c.object-meta.xml
<CustomObject>
    <description>LCF Expression of Interest Form - 1.0</description>
    <label>Form LCF EOI 1.0</label>
    <nameField>
        <displayFormat>EOI-{00000}</displayFormat>
        <label>Form ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Form LCF EOI</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Form_LCF_EOI_1__c/fields/application__c.field-meta.xml
<CustomField>
    <fullName>application__c</fullName>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Form LCF EOI 1.0</relationshipLabel>
    <relationshipName>Form_LCF_EOI_1_0</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Form_LCF_EOI_1__c/fields/lc_first_name__c.field-meta.xml
<CustomField>
    <fullName>lc_first_name__c</fullName>
    <inlineHelpText>First name</inlineHelpText>
    <label>LC - First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Form_LCF_EOI_1__c/fields/or_income_for_year__c.field-meta.xml
<CustomField>
    <fullName>or_income_for_year__c</fullName>
    <inlineHelpText>Total income for the year</inlineHelpText>
    <label>OR - Income for Year</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Form_LCF_EOI_1__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>application__r.EOI_External_Status__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Outcome__c/Outcome__c.object-meta.xml
<CustomObject>
    <description>Metrics by which the success of a project is judged</description>
    <label>Outcome</label>
    <nameField>
        <label>Outcome Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Outcomes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Outcome__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Outcomes</relationshipLabel>
    <relationshipName>Outcomes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Outcome__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Under Review</fullName>
            </value>
            <value>
                <fullName>Live</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Previous_Application__c/Previous_Application__c.object-meta.xml
<CustomObject>
    <label>Previous Application</label>
    <nameField>
        <label>Previous Application Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Previous Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Previous_Application__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Previous Applications</relationshipLabel>
    <relationshipName>Previous_Applications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SIB_Field_Metadata__c/SIB_Field_Metadata__c.object-meta.xml
<CustomObject>
    <description>Life Chances Fund - Field metadata extracted via Metadata API and updated with custom attributes</description>
    <label>SIB Field Metadata</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SIB Field Metadata</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SIB_Field_Metadata__c/fields/Field_Name__c.field-meta.xml
<CustomField>
    <fullName>Field_Name__c</fullName>
    <description>Field API Name</description>
    <inlineHelpText>Field API Name</inlineHelpText>
    <label>Field Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SIB_Field_Metadata__c/fields/Help_Text__c.field-meta.xml
<CustomField>
    <fullName>Help_Text__c</fullName>
    <description>Field Help Text (Form Question Label)</description>
    <inlineHelpText>Field Help Text (Form Question Label)</inlineHelpText>
    <label>Help Text (Question Label)</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SIB_Field_Metadata__c/fields/Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_Name__c</fullName>
    <description>SIB Form Object Name</description>
    <inlineHelpText>SIB Form Object Name</inlineHelpText>
    <label>Object Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SIB_Object_Name</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SIB_Field_Metadata__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Custom field type</description>
    <inlineHelpText>Custom field type</inlineHelpText>
    <label>Type</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/SIB_Object_Name.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Application__c</fullName>
    </customValue>
    <customValue>
        <fullName>Form_LCF_EOI_1__c</fullName>
    </customValue>
    <customValue>
        <fullName>Form_LCF_Full_App_1__c</fullName>
    </customValue>
    <customValue>
        <fullName>Form_LCF_Outcome_1__c</fullName>
    </customValue>
    <customValue>
        <fullName>Form_LCF_Commissioner_1__c</fullName>
    </customValue>
    <customValue>
        <fullName>Form_LCF_Previous_App_1__c</fullName>
    </customValue>
    <customValue>
        <fullName>Form_LCF_Setup_1__c</fullName>
    </customValue>
    <customValue>
        <fullName>Form_LCF_Disengagement_1__c</fullName>
    </customValue>
    <customValue>
        <fullName>Form_LCF_Setup_Investor_1__c</fullName>
    </customValue>
    <customValue>
        <fullName>Form_LCF_Outcome_Payment_1__c</fullName>
    </customValue>
    <customValue>
        <fullName>LCF_Grant__c</fullName>
    </customValue>
    <customValue>
        <fullName>Form_LCF_Grant_Baseline_1__c</fullName>
    </customValue>
    <customValue>
        <fullName>Form_LCF_Grant_Profile_1__c</fullName>
    </customValue>
    <customValue>
        <fullName>Form_LCF_Grant_Outcome_1__c</fullName>
    </customValue>
    <customValue>
        <fullName>Form_LCF_Grant_Annual_Block_1__c</fullName>
    </customValue>
    <customValue>
        <fullName>Form_LCF_Grant_End_1__c</fullName>
    </customValue>
    <customValue>
        <fullName>Form_LCF_Grant_Investor_1</fullName>
    </customValue>
    <customValue>
        <fullName>Form_LCF_Grant_Term_1</fullName>
    </customValue>
    <customValue>
        <fullName>Form_LCF_Grant_Achievement_1__c</fullName>
    </customValue>
    <customValue>
        <fullName>Form_LCF_Outcome_Achievement_1__c</fullName>
    </customValue>
    <customValue>
        <fullName>Form_LCF_Payment_Trigger_1__c</fullName>
    </customValue>
    <customValue>
        <fullName>Form_LCF_Outcome_Metric__c</fullName>
    </customValue>
    <customValue>
        <fullName>Form_LCF_Grant_Payment_Profile_1__c</fullName>
    </customValue>
    <customValue>
        <fullName>Form_LCF_Grant_Payment_History_1__c</fullName>
    </customValue>
    <customValue>
        <fullName>Form_LCF_Grant_Annual_1__c</fullName>
        <isActive>false</isActive>
        <label>Form_LCF_Grant_Annual_1__c</label>
    </customValue>
    <description>Object names of SIB Forms</description>
    <masterLabel>SIB Object Name</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/COF_EOIDataConversionTest.cls
/* _______________________________________________________________________________________________________________
   Name:		COF_EOIDataConversionTest.cls
   Description: Test Class for COF_EOIDataConversionController and COF_EOIDataConversion
					
   Date         Version Author          	Summary of Changes 
   ___________  _______ __________________	______________________________________________________________________
   Apr 2018     1.0     Michael Witchalls	Initial Release 
__________________________________________________________________________________________________________________ */        
@isTest
private class COF_EOIDataConversionTest { 
	private static final String RECORDTYPE = 'Expression of Interest';
	private static final String THEME1 = 'Children\'s services';
	private static final String STAGE = 'Expression of Interest';
	private static final String DRAFT = 'Draft';
	private static final String OBJECTNAME = 'Form_LCF_EOI_1__c';
	private static final String FIELDNAME1 = 'lc_first_name__c';
	private static final String FIELDNAME2 = 'or_income_for_year__c';
	
	@testSetup static void setup() {   	
		// Create an Application
		Application__c a = new Application__c(
			RecordTypeId = Schema.SObjectType.Application__c.getRecordTypeInfosByName().get(RECORDTYPE).getRecordTypeId(),
			application_theme__c = THEME1,
			Application_Stage__c = STAGE,
			Status__c = DRAFT
		);
		insert a;
		// Create Application Questions
		List<Application_Question__c> questions = new List<Application_Question__c>{
			new Application_Question__c(Name = 'Test 1', Question_Number__c = 1, Question__c = 'Question 1', Question_Type__c = 'Short Text'),
			new Application_Question__c(Name = 'Test 2', Question_Number__c = 2, Question__c = 'Question 2', Question_Type__c = 'Currency')
		};
		insert questions;
		// Create Application Answers
		Application_Answer__c ans1 = new Application_Answer__c(
			Application__c = a.Id,
			Application_Question__c = questions[0].Id,
			Short_Text_Answer__c = 'Answer 1',
			Data_Conversion_Form__c = STAGE
		);
		Application_Answer__c ans2 = new Application_Answer__c(
			Application__c = a.Id,
			Application_Question__c = questions[1].Id,
			Currency_Answer__c = 200,
			Data_Conversion_Form__c = STAGE
		);
		List<Application_Answer__c> answers = new List<Application_Answer__c>{ans1, ans2};
		insert answers;
		// Create metadata
		List<SIB_Field_Metadata__c> mdList = new List<SIB_Field_Metadata__c>{
			new SIB_Field_Metadata__c(Object_Name__c = OBJECTNAME, Field_Name__c = FIELDNAME1, Help_Text__c = 'Question 1', Type__c = 'Text'),
			new SIB_Field_Metadata__c(Object_Name__c = OBJECTNAME, Field_Name__c = FIELDNAME2, Help_Text__c = 'Question 2', Type__c = 'Currency')
		};
		insert mdList;
		Application_Commissioner__c comm = new Application_Commissioner__c(
			Application__c = a.Id,
			Organisation_Name__c = 'Test Org',
			Is_Lead_Commissioner__c = 'Yes',
			Last_Name__c = 'Test Name'		
		);
		insert comm;
		Outcome__c outcome = new Outcome__c(
			Application__c = a.Id,
			Name = 'Test Outcome'
		);
		insert outcome;
		Previous_Application__c prevApp = new Previous_Application__c(
			Application__c = a.Id,
			Name = 'Old App'
		);
		insert prevApp;
	}
		
    @isTest static void testit() {
		
        PageReference pageRef = Page.COF_EOIDataConversion;
        Test.setCurrentPage(pageRef);     
        
		Test.startTest();
		COF_EOIDataConversionController con1 = new COF_EOIDataConversionController();
		con1.createEOIData();
		con1.createCommissioners();     	
     	con1.createOutcomes(); 
     	con1.createPreviousApps();
     	Test.stopTest();
     	
     	List<Form_LCF_EOI_1__c> eoiList = [
     		SELECT Name, lc_first_name__c, or_income_for_year__c
     		FROM Form_LCF_EOI_1__c
     	];
     	
      	system.assertEquals(1, eoiList.size());
     	system.assertEquals('Answer 1', eoiList[0].lc_first_name__c);
     	system.assertEquals(200, eoiList[0].or_income_for_year__c);

    }  
    
    
}