force-app/main/default/mdapioutput/objects/Application_Question__c.object
<CustomObject>
    <label>Application Question</label>
    <nameField>
        <label>Application Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Question</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Field_From_Contact_Record__c</fullName>
        <description>This is the API name of the field on the contact record you wish to pull the value from.</description>
        <inlineHelpText>This is the API name of the field on the contact record you wish to pull the value from.</inlineHelpText>
        <label>Field From Contact Record</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field_To_Set_On_Answer__c</fullName>
        <label>Field To Set On Answer</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Short_Text_Answer__c</fullName>
                </value>
                <value>
                    <fullName>Checkbox_Answer__c</fullName>
                </value>
                <value>
                    <fullName>Checkboxes_Answer__c</fullName>
                </value>
                <value>
                    <fullName>Date_Answer__c</fullName>
                </value>
                <value>
                    <fullName>Email_Answer__c</fullName>
                </value>
                <value>
                    <fullName>Multi_Picklist_Answers__c</fullName>
                </value>
                <value>
                    <fullName>Percent_Answer__c</fullName>
                </value>
                <value>
                    <fullName>Picklist_Answer__c</fullName>
                </value>
                <value>
                    <fullName>Text_Answer__c</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/default/mdapioutput/objects/Application_Question_Template__c.object
<CustomObject>
    <label>Application Question Template</label>
    <nameField>
        <displayFormat>AQT-{00000}</displayFormat>
        <label>Application Question Template Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Question Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Application_Question__c</fullName>
        <label>Application Question</label>
        <referenceTo>Application_Question__c</referenceTo>
        <relationshipName>Question_Templates</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Application_Window_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application Window Template</label>
        <referenceTo>Application_Window_Template__c</referenceTo>
        <relationshipLabel>Application Question Templates</relationshipLabel>
        <relationshipName>Question_Templates</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

force-app/main/default/mdapioutput/objects/Application_Window_Template__c.object
<CustomObject>
    <label>Application Window Template</label>
    <nameField>
        <displayFormat>AWT-{0}</displayFormat>
        <label>Iteration Template Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Window Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/mdapioutput/classes/SIB_Utilities.cls
public with sharing class SIB_Utilities {
	public static Map<String, Map<String, Id>> recordTypeIdCache = new Map<String, Map<String, Id>>();

	/*
		This method will be used in SIB_SelfRegController and SIB_ApplicationFormExtension. 
		Using this method here will allow one regex in multiple places and will give an easier way to maintain this.
	*/
	public static Boolean isValidEmail(String email) {
		String emailRegex = '^[a-zA-Z0-9\\.\\!\\#\\$\\%\\&\\*\\/\\=\\?\\^\\_\\+\\-\\`\\{\\|\\}\\~\'._%+-]+@[a-zA-Z0-9\\-.-]+\\.[a-zA-Z]+';
		Pattern myPattern = Pattern.compile(emailRegex);
		Matcher myMatcher = myPattern.matcher(email);
		return myMatcher.matches();
	}

	/*
		This method retrieves all questions where there is a "Field From Contact Record" value populated and returns these in
		a string to be used in a query.
	*/
	public static String generateDefaultFields(Id applicationWindowTemplateId){
		String fieldsToReturn = '';
		for(Application_Question_Template__c singleQuestionTemplate : [
			SELECT Application_Question__r.Field_From_Contact_Record__c, Application_Question__r.Field_To_Set_On_Answer__c
			FROM Application_Question_Template__c
			WHERE Application_Window_Template__r.Id = :applicationWindowTemplateId
			AND Application_Question__r.Field_From_Contact_Record__c != null
			ORDER BY CreatedDate ASC
		]){
			fieldsToReturn += singleQuestionTemplate.Application_Question__r.Field_From_Contact_Record__c + ',';
		}
		fieldsToReturn += 'Id';
		return fieldsToReturn;
	}

	/*
		Utility method to query record type Id's. It stores all record types for a particular object to store them for later use,
		which allows a more effective use than querying the record type each time.
	*/
	public static Id getRecordTypeId(String objName, String rtName) {
		if(!recordTypeIdCache.containsKey(objName)){
			Map<String, Id> valuesToPut = new Map<String, Id>();
			Map<String,Schema.RecordTypeInfo> recordTypeInfo = Schema.getGlobalDescribe().get(objName).getDescribe().getRecordTypeInfosByName();
			for(String recordTypeInfoName : recordTypeInfo.keySet()){
				valuesToPut.put(recordTypeInfoName, recordTypeInfo.get(recordTypeInfoName).getRecordTypeId());
			}
			recordTypeIdCache.put(objName, valuesToPut);
		}
		return recordTypeIdCache.get(objName).get(rtName);
	}

	/*
		This method is used on every page to check if the user is logged in, therefore shielding these pages from external views.
		We need to check that the is no user AND that the user is not the community user.
	*/
	public static PageReference checkLoggedInStatus(){
		PageReference pageReferenceToReturn = 
		UserInfo.getUserId() == null || UserInfo.getUserName().startsWith('social_impact_bonds@') ? 
			returnHomePage() : 
			null;
        return pageReferenceToReturn;
	}   

	/*
		Single method to return the base URL of the site. This can be used in multiple places and allows easier upkeep.
	*/
	public static PageReference returnHomePage(){
		return Page.SIB_Login;
	}
}