force-app/main/default/mdapioutput/objects/Application__c.object
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{00000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SIB_Field_Metadata__c/SIB_Field_Metadata__c.object-meta.xml
<CustomObject>
    <description>Life Chances Fund - Field metadata extracted via Metadata API and updated with custom attributes</description>
    <label>SIB Field Metadata</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SIB Field Metadata</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SIB_Field_Metadata__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Field Description (Guidance)</description>
    <inlineHelpText>Field Description (Guidance)</inlineHelpText>
    <label>Description (Guidance)</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SIB_Field_Metadata__c/fields/Field_Key__c.field-meta.xml
<CustomField>
    <fullName>Field_Key__c</fullName>
    <description>ObjectName.FieldName</description>
    <externalId>true</externalId>
    <inlineHelpText>ObjectName.FieldName</inlineHelpText>
    <label>Field Key</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SIB_Field_Metadata__c/fields/Help_Text__c.field-meta.xml
<CustomField>
    <fullName>Help_Text__c</fullName>
    <description>Field Help Text (Form Question Label)</description>
    <inlineHelpText>Field Help Text (Form Question Label)</inlineHelpText>
    <label>Help Text (Question Label)</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SIB_Field_Metadata__c/fields/Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_Name__c</fullName>
    <description>SIB Form Object Name</description>
    <inlineHelpText>SIB Form Object Name</inlineHelpText>
    <label>Object Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SIB_Object_Name</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SIB_Field_Metadata__c/fields/Relationship_Name__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Name__c</fullName>
    <description>Child Relationship Query Name</description>
    <inlineHelpText>Child Relationship Query Name</inlineHelpText>
    <label>Child Relationship Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/SIB_Object_Name.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Application__c</fullName>
    </customValue>
    <customValue>
        <fullName>Form_LCF_EOI_1__c</fullName>
    </customValue>
    <customValue>
        <fullName>Form_LCF_Full_App_1__c</fullName>
    </customValue>
    <customValue>
        <fullName>Form_LCF_Outcome_1__c</fullName>
    </customValue>
    <customValue>
        <fullName>Form_LCF_Commissioner_1__c</fullName>
    </customValue>
    <customValue>
        <fullName>Form_LCF_Previous_App_1__c</fullName>
    </customValue>
    <customValue>
        <fullName>Form_LCF_Setup_1__c</fullName>
    </customValue>
    <customValue>
        <fullName>Form_LCF_Disengagement_1__c</fullName>
    </customValue>
    <customValue>
        <fullName>Form_LCF_Setup_Investor_1__c</fullName>
    </customValue>
    <customValue>
        <fullName>Form_LCF_Outcome_Payment_1__c</fullName>
    </customValue>
    <customValue>
        <fullName>LCF_Grant__c</fullName>
    </customValue>
    <customValue>
        <fullName>Form_LCF_Grant_Baseline_1__c</fullName>
    </customValue>
    <customValue>
        <fullName>Form_LCF_Grant_Profile_1__c</fullName>
    </customValue>
    <customValue>
        <fullName>Form_LCF_Grant_Outcome_1__c</fullName>
    </customValue>
    <customValue>
        <fullName>Form_LCF_Grant_Annual_Block_1__c</fullName>
    </customValue>
    <customValue>
        <fullName>Form_LCF_Grant_End_1__c</fullName>
    </customValue>
    <customValue>
        <fullName>Form_LCF_Grant_Investor_1</fullName>
    </customValue>
    <customValue>
        <fullName>Form_LCF_Grant_Term_1</fullName>
    </customValue>
    <customValue>
        <fullName>Form_LCF_Grant_Achievement_1__c</fullName>
    </customValue>
    <customValue>
        <fullName>Form_LCF_Outcome_Achievement_1__c</fullName>
    </customValue>
    <customValue>
        <fullName>Form_LCF_Payment_Trigger_1__c</fullName>
    </customValue>
    <customValue>
        <fullName>Form_LCF_Outcome_Metric__c</fullName>
    </customValue>
    <customValue>
        <fullName>Form_LCF_Grant_Payment_Profile_1__c</fullName>
    </customValue>
    <customValue>
        <fullName>Form_LCF_Grant_Payment_History_1__c</fullName>
    </customValue>
    <customValue>
        <fullName>Form_LCF_Grant_Annual_1__c</fullName>
        <isActive>false</isActive>
        <label>Form_LCF_Grant_Annual_1__c</label>
    </customValue>
    <description>Object names of SIB Forms</description>
    <masterLabel>SIB Object Name</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/COF_FieldMetadataControllerTest.cls
/* _______________________________________________________________________________________________________________
   Name:		COF_FieldMetadataControllerTest.cls
   Description: Test Class for COF_FieldMetadataController
					
   Date         Version Author          	Summary of Changes 
   ___________  _______ __________________	______________________________________________________________________
   Mar 2018     1.0     Michael Witchalls	Initial Release 
__________________________________________________________________________________________________________________ */        
@isTest
private class COF_FieldMetadataControllerTest { 
		
    @isTest static void testit() {
		
        PageReference pageRef = Page.COF_RetrieveFieldMetadata;
        Test.setCurrentPage(pageRef);     
        
		Test.startTest();
		ApexPages.StandardController stdcon = new ApexPages.StandardController(new SIB_Field_Metadata__c());
		COF_FieldMetadataController con1 = new COF_FieldMetadataController(stdcon);
		con1.retrieveMetadata();
		con1.viewMetadata();     	
     	Test.stopTest(); 
     	
     	List<SIB_Field_Metadata__c> mdList = [
     		SELECT Name, Object_Name__c, Field_Key__c, Description__c, Help_Text__c, Relationship_Name__c
     		FROM SIB_Field_Metadata__c
     	];
     	
     	// test data included in controller class
     	system.assertEquals(con1.objectNameList.size(),mdList.size());
     	system.assertEquals('Application__c',mdList[0].Object_Name__c);
     	system.assertEquals('Test__r',mdList[0].Relationship_Name__c);

    }  
    
    
}