force-app/main/default/mdapioutput/objects/Application__c.object
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{00000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Application_Stage__c</fullName>
        <label>Application Stage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Expression of Interest</fullName>
                    <default>true</default>
                    <label>Expression of Interest</label>
                </value>
                <value>
                    <fullName>Full Application</fullName>
                </value>
                <value>
                    <fullName>Live Project</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>application_theme__c</fullName>
        <label>Application Theme</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Children's services</fullName>
                </value>
                <value>
                    <fullName>Drug and alcohol dependency</fullName>
                </value>
                <value>
                    <fullName>Early years</fullName>
                </value>
                <value>
                    <fullName>Healthy lives</fullName>
                </value>
                <value>
                    <fullName>Older people's services</fullName>
                </value>
                <value>
                    <fullName>Young people</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contact_Email__c</fullName>
        <label>Contact Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Application</relationshipLabel>
        <relationshipName>Application</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Full_Application_Status__c</fullName>
        <label>Full Application Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Under review (In progress)</fullName>
                </value>
                <value>
                    <fullName>Ready for Approval</fullName>
                </value>
                <value>
                    <fullName>Successful</fullName>
                </value>
                <value>
                    <fullName>Unsuccessful</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/default/objects/Form_LCF_Grant_Achievement_1__c/Form_LCF_Grant_Achievement_1__c.object-meta.xml
<CustomObject>
    <description>Life Chances Fund Grant Management - Achievement Block - 1.0</description>
    <label>Form LCF Grant Achievement Block 1.0</label>
    <nameField>
        <displayFormat>GAB-{00000}</displayFormat>
        <label>Achievement ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LCF Grant Achievements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Form_LCF_Grant_Achievement_1__c/fields/ab_approval_status__c.field-meta.xml
<CustomField>
    <fullName>ab_approval_status__c</fullName>
    <description>Approval status of block</description>
    <inlineHelpText>Approval status of block</inlineHelpText>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Grant_Form_Approval_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Form_LCF_Grant_Achievement_1__c/fields/ab_block_status__c.field-meta.xml
<CustomField>
    <fullName>ab_block_status__c</fullName>
    <description>Processing status of block</description>
    <inlineHelpText>Processing status of block</inlineHelpText>
    <label>Block Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Grant_Form_Block_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Form_LCF_Grant_Achievement_1__c/fields/lcf_grant__c.field-meta.xml
<CustomField>
    <fullName>lcf_grant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Grant parent record</description>
    <inlineHelpText>Grant parent record</inlineHelpText>
    <label>LCF Grant</label>
    <referenceTo>LCF_Grant__c</referenceTo>
    <relationshipLabel>Form LCF Grant Achievement Blocks</relationshipLabel>
    <relationshipName>Form_LCF_Grant_Achievement_Blocks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LCF_Grant__c/LCF_Grant__c.object-meta.xml
<CustomObject>
    <description>Life Changes Fund Grant Management master object</description>
    <label>LCF Grant</label>
    <nameField>
        <displayFormat>GNT-{00000}</displayFormat>
        <label>Grant ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LCF Grants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LCF_Grant__c/fields/ab_block_status__c.field-meta.xml
<CustomField>
    <fullName>ab_block_status__c</fullName>
    <description>Status of latest LCF grant achievement block</description>
    <inlineHelpText>Status of latest LCF grant achievement block</inlineHelpText>
    <label>Outcome Achievement Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Grant_Form_Block_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/LCF_Grant__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>LCF Grants</relationshipLabel>
    <relationshipName>lcf_grants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LCF_Grant__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Project Contact</description>
    <inlineHelpText>Project Contact</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>LCF Grants</relationshipLabel>
    <relationshipName>LCF_Grants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LCF_Grant__c/fields/Contact_Email__c.field-meta.xml
<CustomField>
    <fullName>Contact_Email__c</fullName>
    <description>Project contact email</description>
    <inlineHelpText>Project contact email</inlineHelpText>
    <label>Contact Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/SIB_Information__c/SIB_Information__c.object-meta.xml
<CustomObject>
    <description>Informative text relating to SIB Applications</description>
    <label>SIB Reference Information</label>
    <nameField>
        <label>SIB Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SIB Reference</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SIB_Section_Text__c/SIB_Section_Text__c.object-meta.xml
<CustomObject>
    <description>Rich text used in Section Titles in SIB Forms</description>
    <label>SIB Section Text</label>
    <nameField>
        <label>Text ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SIB Section Text</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SIB_Section_Text__c/fields/Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_Name__c</fullName>
    <description>API Name of Form Object</description>
    <inlineHelpText>API Name of Form Object</inlineHelpText>
    <label>Object Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SIB_Object_Name</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SIB_Section_Text__c/fields/SIB_Reference__c.field-meta.xml
<CustomField>
    <fullName>SIB_Reference__c</fullName>
    <description>SIB Reference Information parent record</description>
    <inlineHelpText>SIB Reference Information parent record</inlineHelpText>
    <label>SIB Reference</label>
    <referenceTo>SIB_Information__c</referenceTo>
    <relationshipLabel>Section Text</relationshipLabel>
    <relationshipName>Section_Text</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SIB_Section_Text__c/fields/Text__c.field-meta.xml
<CustomField>
    <fullName>Text__c</fullName>
    <description>Plain or rich text used in section summaries, page titles etc in SIB Forms</description>
    <inlineHelpText>Plain or rich text used in section summaries, page titles etc in SIB Forms</inlineHelpText>
    <label>Text</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/globalValueSets/Grant_Form_Approval_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Not Submitted</fullName>
        <default>true</default>
        <label>Not Submitted</label>
    </customValue>
    <customValue>
        <fullName>Submitted</fullName>
    </customValue>
    <customValue>
        <fullName>Approved</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
    </customValue>
    <description>Approval status of grant form block</description>
    <masterLabel>Grant Form Approval Status</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Grant_Form_Block_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>NOT STARTED</fullName>
        <default>true</default>
        <label>NOT STARTED</label>
    </customValue>
    <customValue>
        <fullName>IN PROGRESS</fullName>
    </customValue>
    <customValue>
        <fullName>COMPLETE</fullName>
    </customValue>
    <customValue>
        <fullName>HISTORY</fullName>
    </customValue>
    <description>Status of Grant Form Block</description>
    <masterLabel>Grant Form Block Status</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/SIB_Object_Name.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Application__c</fullName>
    </customValue>
    <customValue>
        <fullName>Form_LCF_EOI_1__c</fullName>
    </customValue>
    <customValue>
        <fullName>Form_LCF_Full_App_1__c</fullName>
    </customValue>
    <customValue>
        <fullName>Form_LCF_Outcome_1__c</fullName>
    </customValue>
    <customValue>
        <fullName>Form_LCF_Commissioner_1__c</fullName>
    </customValue>
    <customValue>
        <fullName>Form_LCF_Previous_App_1__c</fullName>
    </customValue>
    <customValue>
        <fullName>Form_LCF_Setup_1__c</fullName>
    </customValue>
    <customValue>
        <fullName>Form_LCF_Disengagement_1__c</fullName>
    </customValue>
    <customValue>
        <fullName>Form_LCF_Setup_Investor_1__c</fullName>
    </customValue>
    <customValue>
        <fullName>Form_LCF_Outcome_Payment_1__c</fullName>
    </customValue>
    <customValue>
        <fullName>LCF_Grant__c</fullName>
    </customValue>
    <customValue>
        <fullName>Form_LCF_Grant_Baseline_1__c</fullName>
    </customValue>
    <customValue>
        <fullName>Form_LCF_Grant_Profile_1__c</fullName>
    </customValue>
    <customValue>
        <fullName>Form_LCF_Grant_Outcome_1__c</fullName>
    </customValue>
    <customValue>
        <fullName>Form_LCF_Grant_Annual_Block_1__c</fullName>
    </customValue>
    <customValue>
        <fullName>Form_LCF_Grant_End_1__c</fullName>
    </customValue>
    <customValue>
        <fullName>Form_LCF_Grant_Investor_1</fullName>
    </customValue>
    <customValue>
        <fullName>Form_LCF_Grant_Term_1</fullName>
    </customValue>
    <customValue>
        <fullName>Form_LCF_Grant_Achievement_1__c</fullName>
    </customValue>
    <customValue>
        <fullName>Form_LCF_Outcome_Achievement_1__c</fullName>
    </customValue>
    <customValue>
        <fullName>Form_LCF_Payment_Trigger_1__c</fullName>
    </customValue>
    <customValue>
        <fullName>Form_LCF_Outcome_Metric__c</fullName>
    </customValue>
    <customValue>
        <fullName>Form_LCF_Grant_Payment_Profile_1__c</fullName>
    </customValue>
    <customValue>
        <fullName>Form_LCF_Grant_Payment_History_1__c</fullName>
    </customValue>
    <customValue>
        <fullName>Form_LCF_Grant_Annual_1__c</fullName>
        <isActive>false</isActive>
        <label>Form_LCF_Grant_Annual_1__c</label>
    </customValue>
    <description>Object names of SIB Forms</description>
    <masterLabel>SIB Object Name</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/LCFGrantControllersTest.cls
/* _______________________________________________________________________________________________________________
   Name:		LCFGrantControllersTest.cls
   Description: Test Class for LCFGrantsController and LCFGrantBlockController
					
   Date         Version Author          	Summary of Changes 
   ___________  _______ __________________	______________________________________________________________________
   May 2018     1.0     Michael Witchalls	Initial Release 
__________________________________________________________________________________________________________________ */        
@isTest
private class LCFGrantControllersTest { 
	private static final String RECORDTYPE = 'Full Application';
	private static final String THEME1 = 'Children\'s services';
	private static final String THEME2 = 'Healthy lives';
	private static final String STAGE = 'Full Application';
	private static final String DRAFT = 'Draft';
	private static final String NOTSUBMITTED = 'Not Submitted';
	private static final String SUBMITTED = 'Submitted';
	private static final String INCOMPLETE = 'INCOMPLETE';
	private static final String INPROGRESS = 'IN PROGRESS';
	private static final String FIRSTNAME = 'Joe';
	private static final String LASTNAME = 'Bloggs';
	private static final String EMAILADDRESS = 'joe.bloggs@email.com';
	
	@testSetup static void setup() {
		// Add section text
		SIB_Information__c info = new SIB_Information__c(Name = 'Life Chances Fund');
		insert info;
		SIB_Section_Text__c text = new SIB_Section_Text__c(
			SIB_Reference__c = info.Id,
			Name = 'Form',
			Object_Name__c = 'Form_LCF_Grant_Achievement_1__c',
			Text__c = 'Form Text'
		);
    	insert text;
		SIB_Section_Text__c text2 = new SIB_Section_Text__c(
			SIB_Reference__c = info.Id,
			Name = 'lcf_grant_user_referral_1',
			Object_Name__c = 'Form_LCF_Grant_Achievement_1__c',
			Text__c = 'Section Text'
		);
    	insert text2;
    	
    	// Create a Contact
    	Contact c = new Contact(
    		FirstName=FIRSTNAME,
    		LastName=LASTNAME,
    		Email = EMAILADDRESS
    	);
    	insert c;
    	
		// Create an Application
		Application__c a = new Application__c(
			RecordTypeId = Schema.SObjectType.Application__c.getRecordTypeInfosByName().get(RECORDTYPE).getRecordTypeId(),
			application_theme__c = THEME1,
			Application_Stage__c = STAGE,
			Full_Application_Status__c = DRAFT,
			Contact__c = c.Id,
			Contact_Email__c = EMAILADDRESS
		);
		insert a;
    	
		// Create a Grant
		LCF_Grant__c g = new LCF_Grant__c(Application__c = a.Id);
		insert g;
		
		// Create a Grant Achievement form
		Form_LCF_Grant_Achievement_1__c f = new Form_LCF_Grant_Achievement_1__c(
			lcf_grant__c = g.Id,
			ab_approval_status__c = NOTSUBMITTED,
			ab_block_status__c = INPROGRESS
		);
		insert f;
	}    
	
    @isTest static void testit() {
    	// lcfgrants?id={application id}
    	// lcfgrantblock?form=lcf_grant_achievement_1&app=APP-01165&grant=GNT-0001
    	Application__c a = [SELECT Id, Name, Contact_Email__c FROM Application__c LIMIT 1];
		
        PageReference pageRef = Page.LCFGrants;
        Test.setCurrentPage(pageRef);     
        ApexPages.currentPage().getParameters().put('id', a.Id);      
          
		Test.startTest();
		ApexPages.StandardController stdcon = new ApexPages.StandardController(a);
		LCFGrantsController con1 = new LCFGrantsController(stdcon);
		con1.newGrantAction();
    	LCF_Grant__c g = [SELECT Id, Name, Application__c, Contact_Email__c FROM LCF_Grant__c LIMIT 1];
    	
    	pageRef = Page.LCFGrantBlock;
    	Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('app', a.Name);      
        ApexPages.currentPage().getParameters().put('grant', g.Name);      
        ApexPages.currentPage().getParameters().put('form', 'lcf_grant_achievement_1'); 
             
    	LCFGrantBlockController con2 = new LCFGrantBlockController();
		con2.initialAction();
		con2.submit();
		con2.viewAll();
		
        ApexPages.currentPage().getParameters().put('section', 'lcf_grant_user_referral_1');      
    	LCFGrantBlockController con3 = new LCFGrantBlockController();
    	con3.initialAction();
		con3.start();
		con3.summaryPage();
     	
     	Test.stopTest();
     	Form_LCF_Grant_Achievement_1__c f = [SELECT Id, ab_approval_status__c FROM Form_LCF_Grant_Achievement_1__c LIMIT 1];    	
        system.assertEquals(SUBMITTED, f.ab_approval_status__c);
    }  
    
    
}