force-app/main/default/mdapioutput/objects/Application__c.object
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{00000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/EOI_Primary_Commissioner__c.field-meta.xml
<CustomField>
    <fullName>EOI_Primary_Commissioner__c</fullName>
    <description>Organisation of EOI Primary Commissioner</description>
    <inlineHelpText>Organisation of EOI Primary Commissioner</inlineHelpText>
    <label>EOI Primary Commissioner</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/EOI_Primary_Commissioner_Region__c.field-meta.xml
<CustomField>
    <fullName>EOI_Primary_Commissioner_Region__c</fullName>
    <description>Region of EOI Primary Commissioner</description>
    <inlineHelpText>Region of EOI Primary Commissioner</inlineHelpText>
    <label>EOI Primary Commissioner Region</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Organisation_Region</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/Full_App_Primary_Commissioner__c.field-meta.xml
<CustomField>
    <fullName>Full_App_Primary_Commissioner__c</fullName>
    <description>Organisation of Full Application Primary Commissioner</description>
    <inlineHelpText>Organisation of Full Application Primary Commissioner</inlineHelpText>
    <label>Full App Primary Commissioner</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Full_App_Primary_Commissioner_Region__c.field-meta.xml
<CustomField>
    <fullName>Full_App_Primary_Commissioner_Region__c</fullName>
    <description>Region of primary commissioner organisation</description>
    <inlineHelpText>Region of primary commissioner organisation</inlineHelpText>
    <label>Full App Primary Commissioner Region</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Organisation_Region</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/Setup_Primary_Stakeholder__c.field-meta.xml
<CustomField>
    <fullName>Setup_Primary_Stakeholder__c</fullName>
    <description>Organisation of Full Award Setup Primary Stakeholder</description>
    <inlineHelpText>Organisation of Full Award Setup Primary Stakeholder</inlineHelpText>
    <label>Setup Primary Stakeholder</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Setup_Primary_Stakeholder_Region__c.field-meta.xml
<CustomField>
    <fullName>Setup_Primary_Stakeholder_Region__c</fullName>
    <description>Region of Full Award Setup primary stakeholder</description>
    <inlineHelpText>Region of Full Award Setup primary stakeholder</inlineHelpText>
    <label>Setup Primary Stakeholder Region</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Organisation_Region</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/mdapioutput/objects/Form_LCF_Commissioner_1__c.object
<CustomObject>
    <description>Life Chances Fund - Full Application - Commissioner - 1.0</description>
    <label>Form LCF Commissioner 1.0</label>
    <nameField>
        <displayFormat>COM-{00000}</displayFormat>
        <label>Commissioner ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Form LCF Commissioner 1.0</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Form LCF Commissioner 1.0</relationshipLabel>
        <relationshipName>commissioners</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>full_application__c</fullName>
        <label>Form LCF Full Application 1.0</label>
        <referenceTo>Form_LCF_Full_App_1__c</referenceTo>
        <relationshipLabel>Form LCF Commissioner 1.0</relationshipLabel>
        <relationshipName>full_application_commissioners</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

force-app/main/default/objects/Form_LCF_Commissioner_1__c/fields/eoi__c.field-meta.xml
<CustomField>
    <fullName>eoi__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Form LCF EOI 1.0</label>
    <referenceTo>Form_LCF_EOI_1__c</referenceTo>
    <relationshipName>eoi_commissioners</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Form_LCF_Commissioner_1__c/fields/full_award_setup__c.field-meta.xml
<CustomField>
    <fullName>full_award_setup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Form LCF Full Award Setup 1.0</label>
    <referenceTo>Form_LCF_Setup_1__c</referenceTo>
    <relationshipLabel>Form LCF Stakeholders</relationshipLabel>
    <relationshipName>setup_stakeholders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Form_LCF_Commissioner_1__c/fields/primary__c.field-meta.xml
<CustomField>
    <fullName>primary__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Primary commissioner</inlineHelpText>
    <label>Primary</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Form_LCF_Commissioner_1__c/fields/st_organisation_name__c.field-meta.xml
<CustomField>
    <fullName>st_organisation_name__c</fullName>
    <inlineHelpText>Name of organisation</inlineHelpText>
    <label>ST - Organisation Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Form_LCF_Commissioner_1__c/fields/st_organisation_region__c.field-meta.xml
<CustomField>
    <fullName>st_organisation_region__c</fullName>
    <description>Please select either &#39;England wide&#39; or one or more regions of England</description>
    <inlineHelpText>What region is the organisation in?</inlineHelpText>
    <label>ST - Organisation Region</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Organisation_Region</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Organisation_Region.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>England wide</fullName>
    </customValue>
    <customValue>
        <fullName>London</fullName>
    </customValue>
    <customValue>
        <fullName>South East</fullName>
    </customValue>
    <customValue>
        <fullName>South West</fullName>
    </customValue>
    <customValue>
        <fullName>East of England</fullName>
    </customValue>
    <customValue>
        <fullName>East Midlands</fullName>
    </customValue>
    <customValue>
        <fullName>West Midlands</fullName>
    </customValue>
    <customValue>
        <fullName>Yorkshire and the Humber</fullName>
    </customValue>
    <customValue>
        <fullName>North West</fullName>
    </customValue>
    <customValue>
        <fullName>North East</fullName>
    </customValue>
    <description>Geography of Organisation (multi-select)</description>
    <masterLabel>Organisation Region</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/COF_CommissionerTriggerHandler.cls
/* _______________________________________________________________________________________________________________
   Name:		COF_CommissionerTriggerHandler.cls
   Description: Trigger actions on Form_LCF_Commissioner records
					
   Date         Version Author          	Summary of Changes 
   ___________  _______ __________________	______________________________________________________________________
   Mar 2018		1.0     Michael Witchalls	Initial Release 
__________________________________________________________________________________________________________________ */
      
public class COF_CommissionerTriggerHandler {
	
	/*
	 *	Purpose: Copy full application primary commissioner fields to parent application record
	 *	History: 
	 *		Mar 2018: Michael Witchalls: Initial Release
	 *
	 */
	public void copyPrimaryCommssionerFields(List<Form_LCF_Commissioner_1__c> itemList) {
		
		Map<ID, Application__c> applicationMap = new Map<ID, Application__c>();
		for (Form_LCF_Commissioner_1__c item: itemList) {
			if (item.primary__c && item.st_organisation_name__c != null) {
				Application__c a = new Application__c(
					Id = item.application__c
				);
				if (item.full_application__c != null) {
					a.Full_App_Primary_Commissioner__c = item.st_organisation_name__c;
					a.Full_App_Primary_Commissioner_Region__c = item.st_organisation_region__c;
				}
				if (item.eoi__c != null) {
					a.EOI_Primary_Commissioner__c = item.st_organisation_name__c;
					a.EOI_Primary_Commissioner_Region__c = item.st_organisation_region__c;
				}		
				if (item.full_award_setup__c != null) {
					a.Setup_Primary_Stakeholder__c = item.st_organisation_name__c;
					a.Setup_Primary_Stakeholder_Region__c = item.st_organisation_region__c;
				}		
				applicationMap.put(a.Id, a);
			}
		}
		
		system.debug('@@applicationMap: '+applicationMap);
		if (applicationMap.size() > 0) update applicationMap.values();
	}   
}