force-app/main/default/mdapioutput/objects/Application__c.object
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{00000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Application_Window_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application Window Template</label>
        <referenceTo>Application_Window_Template__c</referenceTo>
        <relationshipLabel>Application</relationshipLabel>
        <relationshipName>Application</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Application</relationshipLabel>
        <relationshipName>Application</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>EOI Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Under review (In progress)</fullName>
                </value>
                <value>
                    <fullName>Ready for Approval</fullName>
                </value>
                <value>
                    <fullName>Successful</fullName>
                </value>
                <value>
                    <fullName>Unsuccessful</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Theme__c</fullName>
        <formula>IF(NOT(ISBLANK(TEXT(application_theme__c))),
TEXT(application_theme__c),
Application_Window_Template__r.Application_Window__r.Theme__r.Name
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Theme</label>
        <type>Text</type>
    </fields>
</CustomObject>

force-app/main/default/mdapioutput/objects/Application_Window__c.object
<CustomObject>
    <description>Controls whether a theme is accepting applications</description>
    <label>Application Window</label>
    <nameField>
        <label>Application Window Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Windows</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Is_Live__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Live</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Theme__c</fullName>
        <label>Theme</label>
        <referenceTo>Theme__c</referenceTo>
        <relationshipLabel>Application Windows</relationshipLabel>
        <relationshipName>Application_Windows</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

force-app/main/default/mdapioutput/objects/Application_Window_Template__c.object
<CustomObject>
    <label>Application Window Template</label>
    <nameField>
        <displayFormat>AWT-{0}</displayFormat>
        <label>Iteration Template Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Window Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Application_Window__c</fullName>
        <label>Application Window</label>
        <referenceTo>Application_Window__c</referenceTo>
        <relationshipLabel>Application Window Templates</relationshipLabel>
        <relationshipName>Application_Window_Templates</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Theme__c</fullName>
        <formula>Application_Window__r.Theme__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Theme</label>
        <type>Text</type>
    </fields>
</CustomObject>

force-app/main/default/mdapioutput/objects/Theme__c.object
<CustomObject>
    <description>The category under which projects are classified. Applicants interest is initially captured against a theme</description>
    <label>Theme</label>
    <nameField>
        <label>Theme Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Themes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/SIB_NewApplicationController.cls
public with sharing class SIB_NewApplicationController {
	private static final String APPRECORDTYPE = 'Expression of Interest';
    public String selectedTheme{get;set;}
    public Map<String, Id> themeNameToIdMap{get;set;}
    
    //As with all the pages where we require a user to be logged in, we check here if the user is logged in, else return the homepage
    public PageReference checkLoggedInStatus(){
        return SIB_Utilities.checkLoggedInStatus();
    }
    /*
        Loading up controller, getting all possible themes. Generating the map so we can display the repeater.
    */
    public SIB_NewApplicationController() {
        themeNameToIdMap = new Map<String, Id>();
        for(Theme__c theme : [
            SELECT Name, Id
            FROM Theme__c
        ]){
            themeNameToIdMap.put(theme.Name, theme.Id);
        }
    }
    // Sets the selected theme.
    public void setValue(){
        selectedTheme = EncodingUtil.urlDecode(ApexPages.currentPage().getParameters().get('valueToSet'), 'UTF-8');
    }

    /*
        Method which creates an application. 
        It finds all application windows for the selected theme, loops through them, then finds one that is live or starts in the future
        and then creates the application, relates it to the contact and makes it a draft.
        It then forwards the user onto the expression of interest form.
    */
    public PageReference startApplication(){
        Application_Window__c applicationWindow = null;
        List<Application_Window__c> appWindows = [
            SELECT Id, Is_Live__c, Start_Date__c, (
                SELECT Id
                FROM Application_Window_Templates__r
            )
            FROM Application_Window__c
            WHERE Theme__c = :selectedTheme
            ORDER BY End_Date__c ASC
        ];
        for(Application_Window__c applicationWindowToCheck : appWindows){
            applicationWindow = applicationWindowToCheck;
            if(applicationWindowToCheck.Is_Live__c || applicationWindowToCheck.Start_Date__c > Date.today()){
                break;
            }
        }
        List<Contact> contactRecords = Database.query('SELECT Id FROM Contact WHERE Email = \'' + UserInfo.getUserEmail() + '\'');
        Application__c applicationToCreate = new Application__c(
			RecordTypeId = Schema.SObjectType.Application__c.getRecordTypeInfosByName().get(APPRECORDTYPE).getRecordTypeId(),
            Application_Window_Template__c = applicationWindow.Application_Window_Templates__r[0].Id,
            Status__c = 'Draft',
            Contact__c = contactRecords.isEmpty() ? null : contactRecords[0].Id
        );
        insert applicationToCreate;
        return new PageReference('/apex/SIB_ApplicationForm?id=' + applicationToCreate.Id + '&formType=Financial%20health%20and%20fraud%20prevention');
    }
}