force-app/main/default/mdapioutput/objects/Application__c.object
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{00000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Application_Stage__c</fullName>
        <label>Application Stage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Expression of Interest</fullName>
                    <default>true</default>
                    <label>Expression of Interest</label>
                </value>
                <value>
                    <fullName>Full Application</fullName>
                </value>
                <value>
                    <fullName>Live Project</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>application_theme__c</fullName>
        <label>Application Theme</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Children's services</fullName>
                </value>
                <value>
                    <fullName>Drug and alcohol dependency</fullName>
                </value>
                <value>
                    <fullName>Early years</fullName>
                </value>
                <value>
                    <fullName>Healthy lives</fullName>
                </value>
                <value>
                    <fullName>Older people's services</fullName>
                </value>
                <value>
                    <fullName>Young people</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Full_Application_Status__c</fullName>
        <label>Full Application Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Under review (In progress)</fullName>
                </value>
                <value>
                    <fullName>Ready for Approval</fullName>
                </value>
                <value>
                    <fullName>Successful</fullName>
                </value>
                <value>
                    <fullName>Unsuccessful</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/default/objects/Form_LCF_Grant_Outcome_1__c/Form_LCF_Grant_Outcome_1__c.object-meta.xml
<CustomObject>
    <description>Life Chances Fund Grant Management - Outcome - 1.0</description>
    <label>Form LCF Grant Outcome 1.0</label>
    <nameField>
        <displayFormat>GOU-{00000}</displayFormat>
        <label>Outcome ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LCF Grant Outcomes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Form_LCF_Grant_Outcome_1__c/fields/lcf_grant__c.field-meta.xml
<CustomField>
    <fullName>lcf_grant__c</fullName>
    <description>Parent LCF Grant</description>
    <inlineHelpText>Parent LCF Grant</inlineHelpText>
    <label>LCF Grant</label>
    <referenceTo>LCF_Grant__c</referenceTo>
    <relationshipLabel>Form LCF Grant Outcomes</relationshipLabel>
    <relationshipName>grant_outcomes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Form_LCF_Grant_Outcome_1__c/fields/ou_outcome_metrics__c.field-meta.xml
<CustomField>
    <fullName>ou_outcome_metrics__c</fullName>
    <inlineHelpText>Agreed outcome metrics - up to 3</inlineHelpText>
    <label>OU - Outcome Metrics</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Form_LCF_Outcome_Metric_1__c/Form_LCF_Outcome_Metric_1__c.object-meta.xml
<CustomObject>
    <description>Life Chances Fund Grant Management - Outcome Metric - 1.0</description>
    <label>Form LCF Outcome Metric 1.0</label>
    <nameField>
        <displayFormat>MET-{00000}</displayFormat>
        <label>Metric ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LCF Grant Outcome Metrics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Form_LCF_Outcome_Metric_1__c/fields/grant_outcome__c.field-meta.xml
<CustomField>
    <fullName>grant_outcome__c</fullName>
    <label>Form LCF Grant Outcome 1.0</label>
    <referenceTo>Form_LCF_Grant_Outcome_1__c</referenceTo>
    <relationshipLabel>Form LCF Outcome Metrics</relationshipLabel>
    <relationshipName>outcome_metrics</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Form_LCF_Outcome_Metric_1__c/fields/om_description__c.field-meta.xml
<CustomField>
    <fullName>om_description__c</fullName>
    <inlineHelpText>Description</inlineHelpText>
    <label>OM - Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Form_LCF_Outcome_Metric_1__c/fields/om_individual_cohort__c.field-meta.xml
<CustomField>
    <fullName>om_individual_cohort__c</fullName>
    <inlineHelpText>Is the outcome metric measured at individual or at cohort level?</inlineHelpText>
    <label>OM - Indvidual/Cohort</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Individual_Cohort</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/LCF_Grant__c/LCF_Grant__c.object-meta.xml
<CustomObject>
    <description>Life Changes Fund Grant Management master object</description>
    <label>LCF Grant</label>
    <nameField>
        <displayFormat>GNT-{00000}</displayFormat>
        <label>Grant ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LCF Grants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LCF_Grant__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>LCF Grants</relationshipLabel>
    <relationshipName>lcf_grants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Individual_Cohort.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Individual</fullName>
    </customValue>
    <customValue>
        <fullName>Cohort</fullName>
    </customValue>
    <description>Type of Outcome Measure or Metric</description>
    <masterLabel>Individual/Cohort</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/COF_OutcomeMetricTriggerHandlerTest.cls
/* _______________________________________________________________________________________________________________
   Name:		COF_OutcomeMetricTriggerHandlerTest.cls
   Description: Test Class for COF_OutcomeMetricTriggerHandler
					
   Date         Version Author          	Summary of Changes 
   ___________  _______ __________________	______________________________________________________________________
   May 2018     1.0     Michael Witchalls	Initial Release 
__________________________________________________________________________________________________________________ */        
@isTest
private class COF_OutcomeMetricTriggerHandlerTest { 
	private static final String RECORDTYPE = 'Full Application';
	private static final String THEME1 = 'Children\'s services';
	private static final String THEME2 = 'Healthy lives';
	private static final String STAGE = 'Full Application';
	private static final String DRAFT = 'Draft';
	
	@testSetup static void setup() {   	
		// Create an Application
		Application__c a = new Application__c(
			RecordTypeId = Schema.SObjectType.Application__c.getRecordTypeInfosByName().get(RECORDTYPE).getRecordTypeId(),
			application_theme__c = THEME1,
			Application_Stage__c = STAGE,
			Full_Application_Status__c = DRAFT
		);
		insert a;
    	
		// Create a Grant
		LCF_Grant__c g = new LCF_Grant__c(Application__c = a.Id);
		insert g;
    	
		// Create a Grant Outcome
		Form_LCF_Grant_Outcome_1__c go = new Form_LCF_Grant_Outcome_1__c(lcf_grant__c = g.Id);
		insert go;
	}    
	
    @isTest static void testit() {
    	Form_LCF_Grant_Outcome_1__c go = [SELECT Id, ou_outcome_metrics__c FROM Form_LCF_Grant_Outcome_1__c LIMIT 1];
    	
    	Test.startTest();
		// Create Outcome Metrics
		Form_LCF_Outcome_Metric_1__c om1 = new Form_LCF_Outcome_Metric_1__c(
			grant_outcome__c = go.Id,
			om_description__c = 'Metric 1',
			om_individual_cohort__c = 'Individual'
		);
		Form_LCF_Outcome_Metric_1__c om2 = new Form_LCF_Outcome_Metric_1__c(
			grant_outcome__c = go.Id,
			om_description__c = 'Metric 2',
			om_individual_cohort__c = 'Cohort'
		);
		
		List<Form_LCF_Outcome_Metric_1__c> omList = new List<Form_LCF_Outcome_Metric_1__c>{om1, om2};
		insert omList;
		
		om2.om_individual_cohort__c = 'Individual'; 
		update omList;
		
		delete om1;
		undelete om1;
		Test.stopTest();
		
    	go = [SELECT Id, ou_outcome_metrics__c FROM Form_LCF_Grant_Outcome_1__c LIMIT 1];
    	Integer n1 = go.ou_outcome_metrics__c.indexOf('Individual');
    	Integer n2 = go.ou_outcome_metrics__c.lastIndexOf('Individual');
		system.assert(n2 > n1);
    }  
    
}