force-app/main/default/mdapioutput/objects/Application__c.object
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{00000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Application_Stage__c</fullName>
        <label>Application Stage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Expression of Interest</fullName>
                    <default>true</default>
                    <label>Expression of Interest</label>
                </value>
                <value>
                    <fullName>Full Application</fullName>
                </value>
                <value>
                    <fullName>Live Project</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>application_theme__c</fullName>
        <label>Application Theme</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Children's services</fullName>
                </value>
                <value>
                    <fullName>Drug and alcohol dependency</fullName>
                </value>
                <value>
                    <fullName>Early years</fullName>
                </value>
                <value>
                    <fullName>Healthy lives</fullName>
                </value>
                <value>
                    <fullName>Older people's services</fullName>
                </value>
                <value>
                    <fullName>Young people</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Full_Application_Status__c</fullName>
        <label>Full Application Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Under review (In progress)</fullName>
                </value>
                <value>
                    <fullName>Ready for Approval</fullName>
                </value>
                <value>
                    <fullName>Successful</fullName>
                </value>
                <value>
                    <fullName>Unsuccessful</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/default/mdapioutput/objects/Form_LCF_Commissioner_1__c.object
<CustomObject>
    <description>Life Chances Fund - Full Application - Commissioner - 1.0</description>
    <label>Form LCF Commissioner 1.0</label>
    <nameField>
        <displayFormat>COM-{00000}</displayFormat>
        <label>Commissioner ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Form LCF Commissioner 1.0</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Form LCF Commissioner 1.0</relationshipLabel>
        <relationshipName>commissioners</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>full_application__c</fullName>
        <label>Form LCF Full Application 1.0</label>
        <referenceTo>Form_LCF_Full_App_1__c</referenceTo>
        <relationshipLabel>Form LCF Commissioner 1.0</relationshipLabel>
        <relationshipName>full_application_commissioners</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

force-app/main/default/objects/Form_LCF_Commissioner_1__c/fields/eoi__c.field-meta.xml
<CustomField>
    <fullName>eoi__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Form LCF EOI 1.0</label>
    <referenceTo>Form_LCF_EOI_1__c</referenceTo>
    <relationshipName>eoi_commissioners</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Form_LCF_Commissioner_1__c/fields/primary__c.field-meta.xml
<CustomField>
    <fullName>primary__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Primary commissioner</inlineHelpText>
    <label>Primary</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Form_LCF_Commissioner_1__c/fields/st_organisation_name__c.field-meta.xml
<CustomField>
    <fullName>st_organisation_name__c</fullName>
    <inlineHelpText>Name of organisation</inlineHelpText>
    <label>ST - Organisation Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Form_LCF_Commissioner_1__c/recordTypes/EOI.recordType-meta.xml
<RecordType>
    <fullName>EOI</fullName>
    <active>true</active>
    <description>Expression of Interest Commissioner Record Type</description>
    <label>EOI</label>
</RecordType>

force-app/main/default/objects/Form_LCF_Commissioner_1__c/recordTypes/Setup.recordType-meta.xml
<RecordType>
    <fullName>Setup</fullName>
    <active>true</active>
    <description>Stakeholder record used in Full Award Setup form</description>
    <label>Setup</label>
</RecordType>

force-app/main/default/objects/Form_LCF_EOI_1__c/Form_LCF_EOI_1__c.object-meta.xml
<CustomObject>
    <description>LCF Expression of Interest Form - 1.0</description>
    <label>Form LCF EOI 1.0</label>
    <nameField>
        <displayFormat>EOI-{00000}</displayFormat>
        <label>Form ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Form LCF EOI</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Form_LCF_EOI_1__c/fields/application__c.field-meta.xml
<CustomField>
    <fullName>application__c</fullName>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Form LCF EOI 1.0</relationshipLabel>
    <relationshipName>Form_LCF_EOI_1_0</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/mdapioutput/objects/Form_LCF_Full_App_1__c.object
<CustomObject>
    <description>Life Chances Fund - Full Application - 1.0</description>
    <label>Form LCF Full Application 1.0</label>
    <nameField>
        <displayFormat>FAP-{00000}</displayFormat>
        <label>Form ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Form LCF Full Application 1.0</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Form LCF Full Application 1.0</relationshipLabel>
        <relationshipName>Form_LCF_Full_Application_1_0</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ov_services_start_date__c</fullName>
        <inlineHelpText>When would you like your project to start delivering services?</inlineHelpText>
        <label>OV - Services Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>si_themes__c</fullName>
        <inlineHelpText>What is the theme of your project?</inlineHelpText>
        <label>SI - Themes</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Children's services</fullName>
                </value>
                <value>
                    <fullName>Drug and alcohol dependency</fullName>
                </value>
                <value>
                    <fullName>Young people</fullName>
                </value>
                <value>
                    <fullName>Healthy lives</fullName>
                </value>
                <value>
                    <fullName>Older people's services</fullName>
                </value>
                <value>
                    <fullName>Early years</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/default/classes/QuestionsControllerTest.cls
/* _______________________________________________________________________________________________________________
   Name:		QuestionsControllerTest.cls
   Description: Test Class for QuestionsController
					
   Date         Version Author          	Summary of Changes 
   ___________  _______ __________________	______________________________________________________________________
   Jan 2018     1.0     Michael Witchalls	Initial Release 
__________________________________________________________________________________________________________________ */        
@isTest
private class QuestionsControllerTest { 
	private static final String RECORDTYPE = 'Full Application';
	private static final String RECORDTYPE2 = 'EOI';
	private static final String THEME1 = 'Children\'s services';
	private static final String THEME2 = 'Healthy lives';
	private static final String STAGE = 'Full Application';
	private static final String DRAFT = 'Draft';
	
	@testSetup static void setup() {
    	
		// Create an Application
		Application__c a = new Application__c(
			RecordTypeId = Schema.SObjectType.Application__c.getRecordTypeInfosByName().get(RECORDTYPE).getRecordTypeId(),
			application_theme__c = THEME1,
			Application_Stage__c = STAGE,
			Full_Application_Status__c = DRAFT
		);
		insert a;
		// Create a Full Application Form
		Form_LCF_Full_App_1__c f = new Form_LCF_Full_App_1__c(
			application__c = a.Id,
			ov_services_start_date__c = System.Today(),
			si_themes__c = THEME1+';'+THEME2
		);
		insert f;
		// Create a EOI Form
		Form_LCF_EOI_1__c e = new Form_LCF_EOI_1__c(
			application__c = a.Id
		);
		// Create 2 Commissioners
		Form_LCF_Commissioner_1__c c = new Form_LCF_Commissioner_1__c(
			RecordTypeId = Schema.SObjectType.Form_LCF_Commissioner_1__c.getRecordTypeInfosByName().get(RECORDTYPE).getRecordTypeId(),
			application__c = a.Id,
			full_application__c = f.Id,
			st_organisation_name__c = 'Full App Commissioner 1',
			primary__c = true			
		);
		insert c;
		Form_LCF_Commissioner_1__c c2 = new Form_LCF_Commissioner_1__c(
			RecordTypeId = Schema.SObjectType.Form_LCF_Commissioner_1__c.getRecordTypeInfosByName().get(RECORDTYPE2).getRecordTypeId(),
			application__c = a.Id,
			eoi__c = e.Id,
			st_organisation_name__c = 'EOI Commissioner 2',
			primary__c = false			
		);
		insert c2;
	}    
	
    @isTest static void testit() {
    	// questions?app=APP-01118&form=lcf_full_app_1&page=1&section=lcf_full_app_overview_1
    	Application__c a = [SELECT Id, Name FROM Application__c LIMIT 1];
    	Form_LCF_Full_App_1__c f = [SELECT Id, Name FROM Form_LCF_Full_App_1__c LIMIT 1];
		Form_LCF_Commissioner_1__c[] c = [SELECT Id, Name FROM Form_LCF_Commissioner_1__c LIMIT 2];
		
        PageReference pageRef = Page.Questions;
        Test.setCurrentPage(pageRef);     
        ApexPages.currentPage().getParameters().put('app', a.Name);      
        ApexPages.currentPage().getParameters().put('form', 'lcf_full_app_1');      
        ApexPages.currentPage().getParameters().put('section', 'lcf_full_app_overview_1');      
        ApexPages.currentPage().getParameters().put('page', '1');
        ApexPages.currentPage().getParameters().put('zzcompletion', '%2Fapex%2Fquestions%3Fapp%3DAPP-01118%26form%3Dlcf_full_app_1%26section%3Dlcf_full_app_overview_1%26page%3D11');
        
		Test.startTest();
		QuestionsController con1 = new QuestionsController();
		con1.saveContinue();
		con1.saveExit();
		
        ApexPages.currentPage().getParameters().put('page', '2');
		QuestionsController con2 = new QuestionsController();
		con2.copyFromPreviousForm();
		con2.modifyChildIdentifier = c[0].Name;
		con2.removeChildId = c[0].Id;
		con2.addAnother();
		con2.changeChild();
		con2.saveContinue();
     	
        ApexPages.currentPage().getParameters().put('app', a.Name);      
        ApexPages.currentPage().getParameters().put('form', 'lcf_full_app_1');      
        ApexPages.currentPage().getParameters().put('id', c[0].Name);      
        ApexPages.currentPage().getParameters().put('section', 'lcf_full_app_overview_child_1');      
        ApexPages.currentPage().getParameters().put('page', '1');
        ApexPages.currentPage().getParameters().put('zzcompletion', '%2Fapex%2Fquestions%3Fapp%3DAPP-01118%26form%3Dlcf_full_app_1%26section%3Dlcf_full_app_overview_1%26page%3D11');
        QuestionsController con3 = new QuestionsController();

		con2.removeChild();
     	Test.stopTest();
        system.assertEquals(f.Name, con1.targetObject.get('Name'));
		system.assertEquals('Form_LCF_Commissioner_1__c', con2.currentPage.children.target_object);
    }  
    
    
}