force-app/main/default/mdapioutput/objects/Application__c.object
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{00000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Application_Stage__c</fullName>
        <label>Application Stage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Expression of Interest</fullName>
                    <default>true</default>
                    <label>Expression of Interest</label>
                </value>
                <value>
                    <fullName>Full Application</fullName>
                </value>
                <value>
                    <fullName>Live Project</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>application_theme__c</fullName>
        <label>Application Theme</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Children's services</fullName>
                </value>
                <value>
                    <fullName>Drug and alcohol dependency</fullName>
                </value>
                <value>
                    <fullName>Early years</fullName>
                </value>
                <value>
                    <fullName>Healthy lives</fullName>
                </value>
                <value>
                    <fullName>Older people's services</fullName>
                </value>
                <value>
                    <fullName>Young people</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/default/objects/Form_LCF_Grant_Achievement_1__c/Form_LCF_Grant_Achievement_1__c.object-meta.xml
<CustomObject>
    <description>Life Chances Fund Grant Management - Achievement Block - 1.0</description>
    <label>Form LCF Grant Achievement Block 1.0</label>
    <nameField>
        <displayFormat>GAB-{00000}</displayFormat>
        <label>Achievement ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LCF Grant Achievements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Form_LCF_Grant_Achievement_1__c/fields/ab_approval_status__c.field-meta.xml
<CustomField>
    <fullName>ab_approval_status__c</fullName>
    <description>Approval status of block</description>
    <inlineHelpText>Approval status of block</inlineHelpText>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Grant_Form_Approval_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Form_LCF_Grant_Achievement_1__c/fields/ab_block_status__c.field-meta.xml
<CustomField>
    <fullName>ab_block_status__c</fullName>
    <description>Processing status of block</description>
    <inlineHelpText>Processing status of block</inlineHelpText>
    <label>Block Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Grant_Form_Block_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Form_LCF_Grant_Achievement_1__c/fields/lcf_grant__c.field-meta.xml
<CustomField>
    <fullName>lcf_grant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Grant parent record</description>
    <inlineHelpText>Grant parent record</inlineHelpText>
    <label>LCF Grant</label>
    <referenceTo>LCF_Grant__c</referenceTo>
    <relationshipLabel>Form LCF Grant Achievement Blocks</relationshipLabel>
    <relationshipName>Form_LCF_Grant_Achievement_Blocks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LCF_Grant__c/LCF_Grant__c.object-meta.xml
<CustomObject>
    <description>Life Changes Fund Grant Management master object</description>
    <label>LCF Grant</label>
    <nameField>
        <displayFormat>GNT-{00000}</displayFormat>
        <label>Grant ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LCF Grants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LCF_Grant__c/fields/ab_block_status__c.field-meta.xml
<CustomField>
    <fullName>ab_block_status__c</fullName>
    <description>Status of latest LCF grant achievement block</description>
    <inlineHelpText>Status of latest LCF grant achievement block</inlineHelpText>
    <label>Outcome Achievement Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Grant_Form_Block_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/LCF_Grant__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>LCF Grants</relationshipLabel>
    <relationshipName>lcf_grants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Grant_Form_Approval_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Not Submitted</fullName>
        <default>true</default>
        <label>Not Submitted</label>
    </customValue>
    <customValue>
        <fullName>Submitted</fullName>
    </customValue>
    <customValue>
        <fullName>Approved</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
    </customValue>
    <description>Approval status of grant form block</description>
    <masterLabel>Grant Form Approval Status</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Grant_Form_Block_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>NOT STARTED</fullName>
        <default>true</default>
        <label>NOT STARTED</label>
    </customValue>
    <customValue>
        <fullName>IN PROGRESS</fullName>
    </customValue>
    <customValue>
        <fullName>COMPLETE</fullName>
    </customValue>
    <customValue>
        <fullName>HISTORY</fullName>
    </customValue>
    <description>Status of Grant Form Block</description>
    <masterLabel>Grant Form Block Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/COF_GrantBlockSubmittedControllerTest.cls
/* _______________________________________________________________________________________________________________
   Name:		COF_GrantBlockSubmittedControllerTest.cls
   Description: Test Class for COF_GrantBlockSubmittedController
					
   Date         Version Author          	Summary of Changes 
   ___________  _______ __________________	______________________________________________________________________
   May 2018     1.0     Michael Witchalls	Initial Release 
__________________________________________________________________________________________________________________ */        
@isTest
private class COF_GrantBlockSubmittedControllerTest { 
	private static final String COMPLETE = 'COMPLETE';
	private static final String NOTSUBMITTED = 'Not Submitted';
	private static final String SUBMITTED = 'Submitted';
	private static final String INCOMPLETE = 'INCOMPLETE';
	private static final String INPROGRESS = 'IN PROGRESS';
	private static final String RECORDTYPE = 'Full Application';
	private static final String THEME1 = 'Children\'s services';
	private static final String THEME2 = 'Healthy lives';
	private static final String STAGE = 'Full Application';
	
	@testSetup static void setup() {
    	
		// Create an Application
		Application__c a = new Application__c(
			RecordTypeId = Schema.SObjectType.Application__c.getRecordTypeInfosByName().get(RECORDTYPE).getRecordTypeId(),
			application_theme__c = THEME1,
			Application_Stage__c = STAGE
		);
		insert a;
    	
		// Create a Grant
		LCF_Grant__c g = new LCF_Grant__c(Application__c = a.Id);
		insert g;
		
		// Create a Grant Achievement form
		Form_LCF_Grant_Achievement_1__c f = new Form_LCF_Grant_Achievement_1__c(
			lcf_grant__c = g.Id,
			ab_approval_status__c = NOTSUBMITTED,
			ab_block_status__c = INPROGRESS
		);
		insert f;
	}    
	
    @isTest static void testit() {
    	// cof_grantblocksubmitted?form=lcf_grant_achievement_1&app=APP-01165&grant=GNT-0001
    	Application__c a = [SELECT Id, Name FROM Application__c LIMIT 1];
    	LCF_Grant__c g = [SELECT Id, Name FROM LCF_Grant__c LIMIT 1];
		
        PageReference pageRef = Page.COF_GrantBlockSubmitted;
        Test.setCurrentPage(pageRef);     
        ApexPages.currentPage().getParameters().put('app', a.Name);      
        ApexPages.currentPage().getParameters().put('grant', g.Name);      
        ApexPages.currentPage().getParameters().put('form', 'lcf_grant_achievement_1');      
          
		Test.startTest();
		COF_GrantBlockSubmittedController con1 = new COF_GrantBlockSubmittedController();
     	
     	Test.stopTest();
        system.assertEquals(g.Name, con1.grant.get('Name'));
    }  
    
    
}