force-app/main/default/mdapioutput/objects/Application__c.object
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{00000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Application_Window_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application Window Template</label>
        <referenceTo>Application_Window_Template__c</referenceTo>
        <relationshipLabel>Application</relationshipLabel>
        <relationshipName>Application</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Theme__c</fullName>
        <formula>IF(NOT(ISBLANK(TEXT(application_theme__c))),
TEXT(application_theme__c),
Application_Window_Template__r.Application_Window__r.Theme__r.Name
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Theme</label>
        <type>Text</type>
    </fields>
</CustomObject>

force-app/main/default/mdapioutput/objects/Application_Window__c.object
<CustomObject>
    <description>Controls whether a theme is accepting applications</description>
    <label>Application Window</label>
    <nameField>
        <label>Application Window Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Windows</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Is_Live__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Live</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Theme__c</fullName>
        <label>Theme</label>
        <referenceTo>Theme__c</referenceTo>
        <relationshipLabel>Application Windows</relationshipLabel>
        <relationshipName>Application_Windows</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

force-app/main/default/mdapioutput/objects/Application_Window_Template__c.object
<CustomObject>
    <label>Application Window Template</label>
    <nameField>
        <displayFormat>AWT-{0}</displayFormat>
        <label>Iteration Template Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Window Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Application_Window__c</fullName>
        <label>Application Window</label>
        <referenceTo>Application_Window__c</referenceTo>
        <relationshipLabel>Application Window Templates</relationshipLabel>
        <relationshipName>Application_Window_Templates</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Theme__c</fullName>
        <formula>Application_Window__r.Theme__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Theme</label>
        <type>Text</type>
    </fields>
</CustomObject>

force-app/main/default/mdapioutput/objects/Theme__c.object
<CustomObject>
    <description>The category under which projects are classified. Applicants interest is initially captured against a theme</description>
    <label>Theme</label>
    <nameField>
        <label>Theme Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Themes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/SIB_NewApplicationControllerTest.cls
@isTest
private class SIB_NewApplicationControllerTest {
	private static final String THEME1 = 'Children\'s services';
	
	@testSetup static void initData(){
		Theme__c theme = DataFactory.insertTheme(THEME1);
		Application_Window__c aw = DataFactory.createAW(theme.Id);
		//Adding in this line so it go through all the available options on the new controller to find the correct template.
		//TO DO: Add multiple different AWT's and make sure it selects the correct one. For now, this will cover code (and I know the code works)
		aw.Is_Live__c = false;
		insert aw;
		Application_Window_Template__c awt = DataFactory.insertAWT(aw.Id);
		//It queries based on contact email address, so we must always set it equal to the user email running the test.
		DataFactory.insertContact(UserInfo.getUserEmail());
	}

	static testMethod void positiveTesting() {
		SIB_NewApplicationController controller = new SIB_NewApplicationController();
		System.assertEquals(1, controller.themeNameToIdMap.size());
		Theme__c theme = [
			SELECT Name, Id
			FROM Theme__c
			LIMIT 1
		];
		// System.assertEquals(theme.Name, controller.themeNameToIdMap.values()[0]);
		System.assertEquals(theme.Id, controller.themeNameToIdMap.values()[0]);
		ApexPages.currentPage().getParameters().put('valueToSet', theme.Id);
		System.assertEquals(null, controller.selectedTheme);
		controller.setValue();
		System.assertEquals(theme.Id, controller.selectedTheme);
		//Will always equal null as we are testing with a logged in user!
		System.assertEquals(null, controller.checkLoggedInStatus());
		System.assertEquals(0, [
			SELECT COUNT()
			FROM Application__c
		]);
		String startApplicationURL = controller.startApplication().getUrl();
		List<Application__c> apps = [
			SELECT Id
			FROM Application__c
		];
		System.assertEquals(1, apps.size());
		System.assertEquals('/apex/SIB_ApplicationForm?formType=Financial+health+and+fraud+prevention&id=' + apps[0].Id,startApplicationURL);

	}
	
}