force-app/main/default/mdapioutput/objects/Application__c.object
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{00000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/Applicant_Organisation_Name__c.field-meta.xml
<CustomField>
    <fullName>Applicant_Organisation_Name__c</fullName>
    <description>Applicant Organisation copied from EOI/Full Application/Full Award Setup forms</description>
    <inlineHelpText>Applicant Organisation copied from EOI/Full Application/Full Award Setup forms</inlineHelpText>
    <label>Applicant Organisation Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Applicant_Organisation_Sector__c.field-meta.xml
<CustomField>
    <fullName>Applicant_Organisation_Sector__c</fullName>
    <description>Applicant Organisation Sector copied from EOI/Full Application/Full Award Setup forms</description>
    <inlineHelpText>Applicant Organisation Sector copied from EOI/Full Application/Full Award Setup forms</inlineHelpText>
    <label>Applicant Organisation Sector</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sector_of_Organisation</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/Applicant_Organisation_Type__c.field-meta.xml
<CustomField>
    <fullName>Applicant_Organisation_Type__c</fullName>
    <description>Applicant Organisation Type copied from EOI/Full Application/Setup forms</description>
    <inlineHelpText>Applicant Organisation Type copied from EOI/Full Application/Setup forms</inlineHelpText>
    <label>Applicant Organisation Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Organisation_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Name__c</fullName>
    <description>Project name copied from EOI/Full Application/Setup forms</description>
    <inlineHelpText>Project name copied from EOI/Full Application/Setup forms</inlineHelpText>
    <label>Project Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Project_Region__c.field-meta.xml
<CustomField>
    <fullName>Project_Region__c</fullName>
    <description>Project Region copied from EOI/Full Application forms</description>
    <inlineHelpText>Project Region copied from EOI/Full Application forms</inlineHelpText>
    <label>Project Region</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Organisation_Region</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/Project_Value__c.field-meta.xml
<CustomField>
    <fullName>Project_Value__c</fullName>
    <description>Estimated total outcome payments copied from Full Application/Full Award Setup forms</description>
    <inlineHelpText>Estimated total outcome payments copied from Full Application/Full Award Setup forms</inlineHelpText>
    <label>Project Value</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Form_LCF_EOI_1__c/Form_LCF_EOI_1__c.object-meta.xml
<CustomObject>
    <description>LCF Expression of Interest Form - 1.0</description>
    <label>Form LCF EOI 1.0</label>
    <nameField>
        <displayFormat>EOI-{00000}</displayFormat>
        <label>Form ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Form LCF EOI</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Form_LCF_EOI_1__c/fields/application__c.field-meta.xml
<CustomField>
    <fullName>application__c</fullName>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Form LCF EOI 1.0</relationshipLabel>
    <relationshipName>Form_LCF_EOI_1_0</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Form_LCF_EOI_1__c/fields/or_organisation_name__c.field-meta.xml
<CustomField>
    <fullName>or_organisation_name__c</fullName>
    <inlineHelpText>What is the legal name of your organisation?</inlineHelpText>
    <label>OR - Organisation Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Form_LCF_EOI_1__c/fields/or_organisation_sector__c.field-meta.xml
<CustomField>
    <fullName>or_organisation_sector__c</fullName>
    <inlineHelpText>What sector does your organisation fit into?</inlineHelpText>
    <label>OR - Organisation Sector</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sector_of_Organisation</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Form_LCF_EOI_1__c/fields/or_organisation_type__c.field-meta.xml
<CustomField>
    <fullName>or_organisation_type__c</fullName>
    <inlineHelpText>Choose the organisation type that best fits your organisation</inlineHelpText>
    <label>OR - Organisation Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Organisation_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Form_LCF_EOI_1__c/fields/pr_project_name__c.field-meta.xml
<CustomField>
    <fullName>pr_project_name__c</fullName>
    <inlineHelpText>What is the name of your project?</inlineHelpText>
    <label>PR - Project Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Form_LCF_EOI_1__c/fields/pr_project_region__c.field-meta.xml
<CustomField>
    <fullName>pr_project_region__c</fullName>
    <description>Please select either &#39;England wide&#39; or one or more regions of England</description>
    <inlineHelpText>Where will your project take place?</inlineHelpText>
    <label>PR - Project Region</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Organisation_Region</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/mdapioutput/objects/Form_LCF_Full_App_1__c.object
<CustomObject>
    <description>Life Chances Fund - Full Application - 1.0</description>
    <label>Form LCF Full Application 1.0</label>
    <nameField>
        <displayFormat>FAP-{00000}</displayFormat>
        <label>Form ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Form LCF Full Application 1.0</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Form LCF Full Application 1.0</relationshipLabel>
        <relationshipName>Form_LCF_Full_Application_1_0</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ov_organisation_type__c</fullName>
        <inlineHelpText>What type of organisation is the lead applicant?</inlineHelpText>
        <label>OV - Organisation Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Local commissioner</fullName>
                </value>
                <value>
                    <fullName>Service provider</fullName>
                </value>
                <value>
                    <fullName>Intermediary</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ov_project_name__c</fullName>
        <inlineHelpText>What would you like to call your project?</inlineHelpText>
        <label>OV - Project Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

force-app/main/default/objects/Form_LCF_Full_App_1__c/fields/or_name__c.field-meta.xml
<CustomField>
    <fullName>or_name__c</fullName>
    <inlineHelpText>What is the legal name of your organisation?</inlineHelpText>
    <label>OR - Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Form_LCF_Full_App_1__c/fields/ov_organisation_sector__c.field-meta.xml
<CustomField>
    <fullName>ov_organisation_sector__c</fullName>
    <inlineHelpText>What is the organisation sector of the lead applicant?</inlineHelpText>
    <label>OV - Organisation Sector</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sector_of_Organisation</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Form_LCF_Full_App_1__c/fields/ov_project_region__c.field-meta.xml
<CustomField>
    <fullName>ov_project_region__c</fullName>
    <description>Please select either &#39;England wide&#39; or one or more regions of England</description>
    <inlineHelpText>Where will your project take place?</inlineHelpText>
    <label>OV - Project Region</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Organisation_Region</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Form_LCF_Full_App_1__c/fields/Project_Value__c.field-meta.xml
<CustomField>
    <fullName>Project_Value__c</fullName>
    <formula>ov_max_estimated_outcomes_payments__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Project Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Form_LCF_Setup_1__c/Form_LCF_Setup_1__c.object-meta.xml
<CustomObject>
    <description>Life Chances Fund - Full Award Set-Up Form - 1.0</description>
    <label>Form LCF Full Award Setup 1.0</label>
    <nameField>
        <displayFormat>STP-{00000}</displayFormat>
        <label>Form ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Form LCF Full Award Setup 1.0</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Form_LCF_Setup_1__c/fields/ap_lead_applicant_organisation__c.field-meta.xml
<CustomField>
    <fullName>ap_lead_applicant_organisation__c</fullName>
    <description>Legal name of organisation</description>
    <inlineHelpText>Which organisation is the lead applicant for your project now?</inlineHelpText>
    <label>AP - Lead Applicant Organisation</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Form_LCF_Setup_1__c/fields/ap_organisation_sector__c.field-meta.xml
<CustomField>
    <fullName>ap_organisation_sector__c</fullName>
    <inlineHelpText>What is the organisation sector of the lead applicant?</inlineHelpText>
    <label>AP - Organisation Sector</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sector_of_Organisation</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Form_LCF_Setup_1__c/fields/ap_organisation_type__c.field-meta.xml
<CustomField>
    <fullName>ap_organisation_type__c</fullName>
    <inlineHelpText>What type of organisation is the lead applicant?</inlineHelpText>
    <label>AP - Organisation Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Organisation_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Form_LCF_Setup_1__c/fields/ap_project_name__c.field-meta.xml
<CustomField>
    <fullName>ap_project_name__c</fullName>
    <inlineHelpText>What is the new name of your project?</inlineHelpText>
    <label>AP - Project Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Form_LCF_Setup_1__c/fields/application__c.field-meta.xml
<CustomField>
    <fullName>application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Form LCF Full Award Setup 1.0</relationshipLabel>
    <relationshipName>Form_LCF_Full_Award_Setup_1_0</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Form_LCF_Setup_1__c/fields/Project_Value__c.field-meta.xml
<CustomField>
    <fullName>Project_Value__c</fullName>
    <description>Project Value = Outcome Payments Expected</description>
    <formula>sf_outcome_payments_expected__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Project Value = Outcome Payments Expected</inlineHelpText>
    <label>Project Value</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/globalValueSets/Organisation_Region.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>England wide</fullName>
    </customValue>
    <customValue>
        <fullName>London</fullName>
    </customValue>
    <customValue>
        <fullName>South East</fullName>
    </customValue>
    <customValue>
        <fullName>South West</fullName>
    </customValue>
    <customValue>
        <fullName>East of England</fullName>
    </customValue>
    <customValue>
        <fullName>East Midlands</fullName>
    </customValue>
    <customValue>
        <fullName>West Midlands</fullName>
    </customValue>
    <customValue>
        <fullName>Yorkshire and the Humber</fullName>
    </customValue>
    <customValue>
        <fullName>North West</fullName>
    </customValue>
    <customValue>
        <fullName>North East</fullName>
    </customValue>
    <description>Geography of Organisation (multi-select)</description>
    <masterLabel>Organisation Region</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Organisation_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Commissioner</fullName>
    </customValue>
    <customValue>
        <fullName>Service provider</fullName>
    </customValue>
    <customValue>
        <fullName>Intermediary</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <description>Type of Organisation</description>
    <masterLabel>Organisation Type</masterLabel>
</GlobalValueSet>

force-app/main/default/mdapioutput/globalValueSets/Sector_of_Organisation.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Public sector</fullName>
    </customValue>
    <customValue>
        <fullName>Private sector</fullName>
    </customValue>
    <customValue>
        <fullName>Voluntary and community sector</fullName>
    </customValue>
    <customValue>
        <fullName>Social enterprise</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <masterLabel>Sector of Organisation</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/COF_ApplicationTriggerHandler.cls
/* _______________________________________________________________________________________________________________
   Name:		COF_ApplicationTriggerHandler.cls
   Description: Trigger actions on Application records
					
   Date         Version Author          	Summary of Changes 
   ___________  _______ __________________	______________________________________________________________________
   Apr 2018		1.0     Michael Witchalls	Initial Release 
__________________________________________________________________________________________________________________ */
      
public class COF_ApplicationTriggerHandler {
	
	/*
	 *	Purpose: On update of Application__c, copy fields from EOI, Full Application and Full Award Setup forms
	 *	History: 
	 *		Apr 2018: Michael Witchalls: Initial Release 
	 *
	 */
	public void copyFieldsFromForms(Map<ID,Application__c> itemMap) {
		Map<ID, Form_LCF_EOI_1__c> eoiMap = new Map<ID, Form_LCF_EOI_1__c>();
		Map<ID, Form_LCF_Full_App_1__c> fullAppMap = new Map<ID, Form_LCF_Full_App_1__c>();
		Map<ID, Form_LCF_Setup_1__c> setupMap = new Map<ID, Form_LCF_Setup_1__c>();
		
		for (Form_LCF_EOI_1__c eoiForm: [
			SELECT 
				Id, application__c, pr_project_name__c, pr_project_region__c,
				or_organisation_name__c, or_organisation_type__c, or_organisation_sector__c 
			FROM
				Form_LCF_EOI_1__c
			WHERE
				application__c IN :itemMap.keySet()
		]) {
			eoiMap.put(eoiForm.application__c, eoiForm);
		}
		
		for (Form_LCF_Full_App_1__c fullAppForm: [
			SELECT 
				Id, application__c, ov_project_name__c, ov_project_region__c, Project_Value__c, 
				or_name__c, ov_organisation_type__c, ov_organisation_sector__c
			FROM
				Form_LCF_Full_App_1__c
			WHERE
				application__c IN :itemMap.keySet()
		]) {
			fullAppMap.put(fullAppForm.application__c, fullAppForm);
		}
		
		for (Form_LCF_Setup_1__c setupForm: [
			SELECT 
				Id, application__c, ap_project_name__c, Project_Value__c, 
				ap_lead_applicant_organisation__c, ap_organisation_type__c, ap_organisation_sector__c
			FROM
				Form_LCF_Setup_1__c
			WHERE
				application__c IN :itemMap.keySet()
		]) {
			setupMap.put(setupForm.application__c, setupForm);
		}
		
		for (Application__c app: itemMap.values()) {
			Form_LCF_EOI_1__c eoiForm = eoiMap.get(app.Id);
			Form_LCF_Full_App_1__c fullAppForm = fullAppMap.get(app.Id);
			Form_LCF_Setup_1__c setupForm = setupMap.get(app.Id);
			
			if (setupForm != null && setupForm.ap_project_name__c != null) {
				app.Project_Name__c = setupForm.ap_project_name__c;
			} else if (fullAppForm != null && fullAppForm.ov_project_name__c != null) {
				app.Project_Name__c = fullAppForm.ov_project_name__c;
			} else if (eoiForm != null && eoiForm.pr_project_name__c != null) {
				app.Project_Name__c = eoiForm.pr_project_name__c;
			}
			
			if (fullAppForm != null && fullAppForm.ov_project_region__c != null) {
				app.Project_Region__c = fullAppForm.ov_project_region__c;
			} else if (eoiForm != null && eoiForm.pr_project_region__c != null) {
				app.Project_Region__c = eoiForm.pr_project_region__c; 
			}
			
			if (setupForm != null && setupForm.Project_Value__c != null) {
				app.Project_Value__c = setupForm.Project_Value__c;
			} else if (fullAppForm  != null && fullAppForm.Project_Value__c != null) {
				app.Project_Value__c = fullAppForm.Project_Value__c; 
			}
			
			if (setupForm != null && setupForm.ap_lead_applicant_organisation__c != null) {
				app.Applicant_Organisation_Name__c = setupForm.ap_lead_applicant_organisation__c;
			} else if (fullAppForm != null && fullAppForm.or_name__c != null) {
				app.Applicant_Organisation_Name__c = fullAppForm.or_name__c;
			} else if (eoiForm != null && eoiForm.or_organisation_name__c != null) {
				app.Applicant_Organisation_Name__c = eoiForm.or_organisation_name__c;
			}
			
			if (setupForm != null && setupForm.ap_organisation_type__c != null) {
				app.Applicant_Organisation_Type__c = setupForm.ap_organisation_type__c;
			} else if (fullAppForm != null && fullAppForm.ov_organisation_type__c != null) {
				app.Applicant_Organisation_Type__c = fullAppForm.ov_organisation_type__c;
			} else if (eoiForm != null && eoiForm.or_organisation_type__c != null) {
				app.Applicant_Organisation_Type__c = eoiForm.or_organisation_type__c;
			}
			
			if (setupForm != null && setupForm.ap_organisation_sector__c != null) {
				app.Applicant_Organisation_Sector__c = setupForm.ap_organisation_sector__c;
			} else if (fullAppForm != null && fullAppForm.ov_organisation_sector__c != null) {
				app.Applicant_Organisation_Sector__c = fullAppForm.ov_organisation_sector__c;
			} else if (eoiForm != null && eoiForm.or_organisation_sector__c != null) {
				app.Applicant_Organisation_Sector__c = eoiForm.or_organisation_sector__c;
			}
		}
		
	}
}