force-app/main/default/mdapioutput/objects/Application__c.object
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{00000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Application</relationshipLabel>
        <relationshipName>Application</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Eligible_for_Full_Application__c</fullName>
        <formula>IF(
AND(
 Dev_Form_External_Status__c == 'Successful',
 EOI_External_Status__c == 'Successful',
 Identity_Check_External_Status__c == 'Successful'
), TRUE, FALSE
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Eligible for Full Application</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Full_Application_Status__c</fullName>
        <label>Full Application Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Under review (In progress)</fullName>
                </value>
                <value>
                    <fullName>Ready for Approval</fullName>
                </value>
                <value>
                    <fullName>Successful</fullName>
                </value>
                <value>
                    <fullName>Unsuccessful</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Theme__c</fullName>
        <formula>IF(NOT(ISBLANK(TEXT(application_theme__c))),
TEXT(application_theme__c),
Application_Window_Template__r.Application_Window__r.Theme__r.Name
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Theme</label>
        <type>Text</type>
    </fields>
</CustomObject>

force-app/main/default/mdapioutput/objects/Theme__c.object
<CustomObject>
    <description>The category under which projects are classified. Applicants interest is initially captured against a theme</description>
    <label>Theme</label>
    <nameField>
        <label>Theme Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Themes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/mdapioutput/objects/User.object
<CustomObject>
    <fields>
        <fullName>Eligible_for_Full_Application__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Community user is eligible for the Full Application Form</inlineHelpText>
        <label>Eligible for Full Application</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

force-app/main/default/classes/ApplicationsController.cls
/**
 * Applications Controller
 */
public with sharing class ApplicationsController extends COF_PageController {

	public COF_Form form {get;set;}
	public List<SObject> applications {get;set;} 

	public ApplicationsController() {			
		// M.Witchalls Jan 2018: Limit query to eligible applications
		//                       and also limit to applications owned if a Customer user
		//
		String constraint = 'WHERE Eligible_for_Full_Application__c = TRUE';
		User u = [SELECT ContactId FROM User WHERE Id = :UserInfo.getUserId()];
		if (u.ContactId != null) {
			constraint += ' AND Contact__c = \''+u.ContactId+'\'';
		}

		// Get the application
        List<String> fields = new List<String>();
        fields.add('Name');
        fields.add('Theme__c');
        fields.add('Full_Application_Status__c');
        this.applications = Query.objects('Application__c', fields, constraint);
        // throw exception
        System.debug(this.applications);
	}

//    public PageReference newApplication() {
//
//        PageReference nextPage = Page.new;
//        nextPage.setRedirect(true);
//        return nextPage;
//    }

}