force-app/main/default/mdapioutput/objects/Application__c.object
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{00000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Contact_Email__c</fullName>
        <label>Contact Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>EOI Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Under review (In progress)</fullName>
                </value>
                <value>
                    <fullName>Ready for Approval</fullName>
                </value>
                <value>
                    <fullName>Successful</fullName>
                </value>
                <value>
                    <fullName>Unsuccessful</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Theme__c</fullName>
        <formula>IF(NOT(ISBLANK(TEXT(application_theme__c))),
TEXT(application_theme__c),
Application_Window_Template__r.Application_Window__r.Theme__r.Name
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Theme</label>
        <type>Text</type>
    </fields>
</CustomObject>

force-app/main/default/objects/Form_LCF_Grant_Achievement_1__c/Form_LCF_Grant_Achievement_1__c.object-meta.xml
<CustomObject>
    <description>Life Chances Fund Grant Management - Achievement Block - 1.0</description>
    <label>Form LCF Grant Achievement Block 1.0</label>
    <nameField>
        <displayFormat>GAB-{00000}</displayFormat>
        <label>Achievement ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LCF Grant Achievements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Form_LCF_Grant_Achievement_1__c/fields/ab_block_status__c.field-meta.xml
<CustomField>
    <fullName>ab_block_status__c</fullName>
    <description>Processing status of block</description>
    <inlineHelpText>Processing status of block</inlineHelpText>
    <label>Block Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Grant_Form_Block_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Form_LCF_Grant_Achievement_1__c/fields/lcf_grant__c.field-meta.xml
<CustomField>
    <fullName>lcf_grant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Grant parent record</description>
    <inlineHelpText>Grant parent record</inlineHelpText>
    <label>LCF Grant</label>
    <referenceTo>LCF_Grant__c</referenceTo>
    <relationshipLabel>Form LCF Grant Achievement Blocks</relationshipLabel>
    <relationshipName>Form_LCF_Grant_Achievement_Blocks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Form_LCF_Grant_Achievement_1__c/fields/Theme__c.field-meta.xml
<CustomField>
    <fullName>Theme__c</fullName>
    <formula>lcf_grant__r.Theme__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Theme</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Form_LCF_Grant_Annual_Block_1__c/Form_LCF_Grant_Annual_Block_1__c.object-meta.xml
<CustomObject>
    <description>Life Chances Fund Grant Management - Annual Monitoring - 1.0</description>
    <label>Form LCF Grant Annual Block 1.0</label>
    <nameField>
        <displayFormat>GAM-{00000}</displayFormat>
        <label>Block ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LCF Grant Annual Monitoring</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Form_LCF_Grant_Annual_Block_1__c/fields/am_block_status__c.field-meta.xml
<CustomField>
    <fullName>am_block_status__c</fullName>
    <description>Processing status of block</description>
    <inlineHelpText>Processing status of block</inlineHelpText>
    <label>Block Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Grant_Form_Block_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Form_LCF_Grant_Annual_Block_1__c/fields/lcf_grant__c.field-meta.xml
<CustomField>
    <fullName>lcf_grant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Parent LCF Grant</description>
    <inlineHelpText>Parent LCF Grant</inlineHelpText>
    <label>LCF Grant</label>
    <referenceTo>LCF_Grant__c</referenceTo>
    <relationshipLabel>Form LCF Grant Annual Blocks</relationshipLabel>
    <relationshipName>Form_LCF_Grant_Annual_Blocks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Form_LCF_Grant_Baseline_1__c/Form_LCF_Grant_Baseline_1__c.object-meta.xml
<CustomObject>
    <description>Life Chances Fund Grant Management - Baseline Block - 1.0</description>
    <label>Form LCF Grant Baseline Block 1.0</label>
    <nameField>
        <displayFormat>GBB-{00000}</displayFormat>
        <label>Baseline ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LCF Grant Baseline Blocks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Form_LCF_Grant_Baseline_1__c/fields/bb_block_status__c.field-meta.xml
<CustomField>
    <fullName>bb_block_status__c</fullName>
    <description>Processing status of block</description>
    <inlineHelpText>Processing status of block</inlineHelpText>
    <label>Block Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Grant_Form_Block_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Form_LCF_Grant_Baseline_1__c/fields/bb_issue_status__c.field-meta.xml
<CustomField>
    <fullName>bb_issue_status__c</fullName>
    <description>Issue status of block created by funding officer</description>
    <inlineHelpText>Issue status of block created by funding officer</inlineHelpText>
    <label>Issue Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Grant_Block_Issue_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Form_LCF_Grant_Baseline_1__c/fields/lcf_grant__c.field-meta.xml
<CustomField>
    <fullName>lcf_grant__c</fullName>
    <description>Grant parent record</description>
    <inlineHelpText>Grant parent record</inlineHelpText>
    <label>LCF Grant</label>
    <referenceTo>LCF_Grant__c</referenceTo>
    <relationshipLabel>LCF Grant Baseline Blocks</relationshipLabel>
    <relationshipName>Form_LCF_Grant_Baseline_Blocks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Form_LCF_Grant_Payment_Profile_1__c/Form_LCF_Grant_Payment_Profile_1__c.object-meta.xml
<CustomObject>
    <description>Life Chances Fund Grant Management - Payment Profile - 1.0</description>
    <label>Form LCF Grant Payment Profile 1.0</label>
    <nameField>
        <displayFormat>GPP-{00000}</displayFormat>
        <label>Profile ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LCF Grant Payment Profiles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Form_LCF_Grant_Payment_Profile_1__c/fields/lcf_grant__c.field-meta.xml
<CustomField>
    <fullName>lcf_grant__c</fullName>
    <description>Parent LCF Grant</description>
    <inlineHelpText>Parent LCF Grant</inlineHelpText>
    <label>LCF Grant</label>
    <referenceTo>LCF_Grant__c</referenceTo>
    <relationshipLabel>Form LCF Grant Payment Profiles</relationshipLabel>
    <relationshipName>Form_LCF_Grant_Payment_Profiles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Form_LCF_Grant_Payment_Profile_1__c/fields/pp_block_status__c.field-meta.xml
<CustomField>
    <fullName>pp_block_status__c</fullName>
    <description>Processing status of block</description>
    <inlineHelpText>Processing status of block</inlineHelpText>
    <label>Block Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Grant_Form_Block_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Form_LCF_Grant_Payment_Profile_1__c/fields/pp_issue_status__c.field-meta.xml
<CustomField>
    <fullName>pp_issue_status__c</fullName>
    <description>Issue status of block created by funding officer</description>
    <inlineHelpText>Issue status of block created by funding officer</inlineHelpText>
    <label>Issue Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Grant_Block_Issue_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/LCF_Grant__c/LCF_Grant__c.object-meta.xml
<CustomObject>
    <description>Life Changes Fund Grant Management master object</description>
    <label>LCF Grant</label>
    <nameField>
        <displayFormat>GNT-{00000}</displayFormat>
        <label>Grant ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LCF Grants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LCF_Grant__c/fields/ab_block_status__c.field-meta.xml
<CustomField>
    <fullName>ab_block_status__c</fullName>
    <description>Status of latest LCF grant achievement block</description>
    <inlineHelpText>Status of latest LCF grant achievement block</inlineHelpText>
    <label>Outcome Achievement Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Grant_Form_Block_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/LCF_Grant__c/fields/am_block_status__c.field-meta.xml
<CustomField>
    <fullName>am_block_status__c</fullName>
    <description>Status of latest annual monitoring block</description>
    <inlineHelpText>Status of latest annual monitoring block</inlineHelpText>
    <label>Annual Monitoring Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Grant_Form_Block_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/LCF_Grant__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>LCF Grants</relationshipLabel>
    <relationshipName>lcf_grants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LCF_Grant__c/fields/Application_ID__c.field-meta.xml
<CustomField>
    <fullName>Application_ID__c</fullName>
    <formula>Application__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Application ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LCF_Grant__c/fields/bb_block_status__c.field-meta.xml
<CustomField>
    <fullName>bb_block_status__c</fullName>
    <description>Status of offer letter baseline block</description>
    <inlineHelpText>Status of offer letter baseline block</inlineHelpText>
    <label>Baseline Block Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Grant_Form_Block_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/LCF_Grant__c/fields/bb_issue_status__c.field-meta.xml
<CustomField>
    <fullName>bb_issue_status__c</fullName>
    <description>Issue status of baseline block</description>
    <inlineHelpText>Issue status of baseline block</inlineHelpText>
    <label>Baseline Issue Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Grant_Block_Issue_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/LCF_Grant__c/fields/Contact_Email__c.field-meta.xml
<CustomField>
    <fullName>Contact_Email__c</fullName>
    <description>Project contact email</description>
    <inlineHelpText>Project contact email</inlineHelpText>
    <label>Contact Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/LCF_Grant__c/fields/pp_block_status__c.field-meta.xml
<CustomField>
    <fullName>pp_block_status__c</fullName>
    <description>Status of latest LCF payment profile block</description>
    <inlineHelpText>Status of latest LCF payment profile block</inlineHelpText>
    <label>Payment Profile Block Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Grant_Form_Block_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/LCF_Grant__c/fields/pp_issue_status__c.field-meta.xml
<CustomField>
    <fullName>pp_issue_status__c</fullName>
    <description>Issue Status of latest LCF payment profile block</description>
    <inlineHelpText>Issue Status of latest LCF payment profile block</inlineHelpText>
    <label>Payment Profile Issue Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Grant_Block_Issue_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/LCF_Grant__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of project associated with SIB Grant</description>
    <inlineHelpText>Status of project associated with SIB Grant</inlineHelpText>
    <label>Grant Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>Award Issued</fullName>
            </value>
            <value>
                <fullName>Award Accepted</fullName>
            </value>
            <value>
                <fullName>Project Launched</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/LCF_Grant__c/fields/Theme__c.field-meta.xml
<CustomField>
    <fullName>Theme__c</fullName>
    <description>Theme of application project</description>
    <formula>Application__r.Theme__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Theme of application project</inlineHelpText>
    <label>Theme</label>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Grant_Block_Issue_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Draft</fullName>
        <default>true</default>
        <label>Draft</label>
    </customValue>
    <customValue>
        <fullName>Issued</fullName>
    </customValue>
    <description>Issue status of block created by funding officer</description>
    <masterLabel>Grant Block Issue Status</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Grant_Form_Block_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>NOT STARTED</fullName>
        <default>true</default>
        <label>NOT STARTED</label>
    </customValue>
    <customValue>
        <fullName>IN PROGRESS</fullName>
    </customValue>
    <customValue>
        <fullName>COMPLETE</fullName>
    </customValue>
    <customValue>
        <fullName>HISTORY</fullName>
    </customValue>
    <description>Status of Grant Form Block</description>
    <masterLabel>Grant Form Block Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/LCFGrantsController.cls
/* __________________________________________________________________________________________________________________
   Name:		LCFGrantsController.cls
   Description: Controller class for LCF Grants page
					
   Date         Version Author          		Summary of Changes 
   ___________  _______ __________________		_____________________________________________________________________
   Apr 2018	    1.0    	M.Witchalls,Westbrook	Initial Release 
   Jun 2018 	1.1		M.Witchalls,Westbrook	Update Block Status with Approval Status when block has been submitted
   												Update Block Status with Issue Status when block has been issued
__________________________________________________________________________________________________________________ */        
public with sharing class LCFGrantsController extends COF_PageController {
	private static final String GRANTOBJECT = 'LCF_Grant__c';
    private static final String CONTACTEMAILFIELD = 'Contact_Email__c';
	private static final String[] QUERYFIELDS = new List<String>{'Name', 'Theme__c', 'Application__c', 'Application_ID__c'};
	private static final String[] STATUSFIELDS = new List<String>{
		'Status__c', 
		'bb_block_status__c', 
		'pp_block_status__c',
		'ab_block_status__c',
		'am_block_status__c'
	};
	private static final String baselineBlockQuery = '(SELECT bb_block_status__c, bb_issue_status__c FROM Form_LCF_Grant_Baseline_Blocks__r WHERE bb_block_status__c != \'HISTORY\')';
	private static final String paymentProfileQuery = '(SELECT pp_block_status__c, pp_issue_status__c FROM Form_LCF_Grant_Payment_Profiles__r WHERE pp_block_status__c != \'HISTORY\')';
	private static final String achievementQuery = '(SELECT ab_block_status__c, ab_approval_status__c FROM Form_LCF_Grant_Achievement_Blocks__r WHERE ab_block_status__c != \'HISTORY\')';
	private static final String annualBlockQuery = '(SELECT am_block_status__c, am_approval_status__c FROM Form_LCF_Grant_Annual_Blocks__r WHERE am_block_status__c != \'HISTORY\')';
	private static final String COMPLETE = 'COMPLETE';
	private static final String NOTSUBMITTED = 'Not Submitted';
	private static final String DRAFT = 'Draft';
	
	public COF_Form form {get;set;}
	public List<SObject> grants {get;set;} 
	public SObject thisGrant {get;set;}
    private ApexPages.StandardController stdCon;
    public String idString {get;set;}
	private String constraint;
	private List<String> fields;
		
	public LCFGrantsController(ApexPages.StandardController stdController) { 	
		this.idString = ApexPages.currentPage().getParameters().get('id');   		
		if (String.isNotBlank(this.idString)) {
			this.constraint = 'WHERE Application__c = \''+idString+'\'';
		} else {
			User u = [SELECT ContactId FROM User WHERE Id = :UserInfo.getUserId()];	
			if (u.ContactId != null) {
				this.constraint = 'WHERE Contact__c = \''+u.ContactId+'\' AND Status__c = \'Project Launched\'';
			}
		}
        // Get the grant(s)	
        this.fields = new List<String>();
        this.fields.addAll(QUERYFIELDS);
        this.fields.addAll(STATUSFIELDS);
        this.fields.add(baselineBlockQuery);
        this.fields.add(paymentProfileQuery);
        this.fields.add(achievementQuery);
        this.fields.add(annualBlockQuery);
        this.grants = Query.objects(GRANTOBJECT, this.fields, constraint);
	}

    public PageReference newGrantAction() {
        if (this.idString != null && this.grants.size() == 0) { 
        	List<Application__c> apps = [SELECT Contact__c, Contact_Email__c FROM Application__c WHERE Id = :this.idString];
        	if (apps.size() > 0) {
        		String contactId = apps[0].Contact__c;
        		String contactEmail = apps[0].Contact_Email__c;
        		Query.createObject(GRANTOBJECT, this.idString, contactId, CONTACTEMAILFIELD, contactEmail);       		
        	}
	        // Get the grant(s)	
	        this.grants = Query.objects(GRANTOBJECT, this.fields, constraint);
        }   
 	    if (this.grants.size() > 0) {
 	    	this.thisGrant = grants[0];
 	    	this.idString = (String)this.thisGrant.get('Application__c');
 	    }
        System.debug('###grants: '+this.grants);
        
        // M.Witchalls June 2018 - Update Block Status with Approval Status when block has been submitted
        // M.Witchalls June 2018 - Update Block Status with Issue Status when block has been issued
        for (SObject obj: this.grants) { 
        	LCF_Grant__c grant = (LCF_Grant__c) obj;
        	if (grant.Form_LCF_Grant_Baseline_Blocks__r.size() > 0) {
        		grant.bb_block_status__c = grant.Form_LCF_Grant_Baseline_Blocks__r[0].bb_block_status__c;
        		if (grant.bb_block_status__c == COMPLETE && grant.Form_LCF_Grant_Baseline_Blocks__r[0].bb_issue_status__c != DRAFT) {
        			grant.bb_block_status__c = grant.Form_LCF_Grant_Baseline_Blocks__r[0].bb_issue_status__c;
        		}
        	}
        	if (grant.Form_LCF_Grant_Payment_Profiles__r.size() > 0) {
        		grant.pp_block_status__c = grant.Form_LCF_Grant_Payment_Profiles__r[0].pp_block_status__c;
        		if (grant.pp_block_status__c == COMPLETE && grant.Form_LCF_Grant_Payment_Profiles__r[0].pp_issue_status__c != DRAFT) {
        			grant.pp_block_status__c = grant.Form_LCF_Grant_Payment_Profiles__r[0].pp_issue_status__c;
        		}
        	}
        	if (grant.Form_LCF_Grant_Achievement_Blocks__r.size() > 0) {
        		grant.ab_block_status__c = grant.Form_LCF_Grant_Achievement_Blocks__r[0].ab_block_status__c;
        		if (grant.ab_block_status__c == COMPLETE && grant.Form_LCF_Grant_Achievement_Blocks__r[0].ab_approval_status__c != NOTSUBMITTED) {
        			grant.ab_block_status__c = grant.Form_LCF_Grant_Achievement_Blocks__r[0].ab_approval_status__c;
        		}
        	}
        	if (grant.Form_LCF_Grant_Annual_Blocks__r.size() > 0) {
        		grant.am_block_status__c = grant.Form_LCF_Grant_Annual_Blocks__r[0].am_block_status__c;
        		if (grant.am_block_status__c == COMPLETE && grant.Form_LCF_Grant_Annual_Blocks__r[0].am_approval_status__c != NOTSUBMITTED) {
        			grant.am_block_status__c = grant.Form_LCF_Grant_Annual_Blocks__r[0].am_approval_status__c;
        		}
        	}
        }
		return SIB_Utilities.checkLoggedInStatus();
    }

}