force-app/main/default/mdapioutput/objects/Application__c.object
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{00000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Application_Stage__c</fullName>
        <label>Application Stage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Expression of Interest</fullName>
                    <default>true</default>
                    <label>Expression of Interest</label>
                </value>
                <value>
                    <fullName>Full Application</fullName>
                </value>
                <value>
                    <fullName>Live Project</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>application_theme__c</fullName>
        <label>Application Theme</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Children's services</fullName>
                </value>
                <value>
                    <fullName>Drug and alcohol dependency</fullName>
                </value>
                <value>
                    <fullName>Early years</fullName>
                </value>
                <value>
                    <fullName>Healthy lives</fullName>
                </value>
                <value>
                    <fullName>Older people's services</fullName>
                </value>
                <value>
                    <fullName>Young people</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Full_Application_Status__c</fullName>
        <label>Full Application Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Under review (In progress)</fullName>
                </value>
                <value>
                    <fullName>Ready for Approval</fullName>
                </value>
                <value>
                    <fullName>Successful</fullName>
                </value>
                <value>
                    <fullName>Unsuccessful</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/default/mdapioutput/objects/Form_LCF_Full_App_1__c.object
<CustomObject>
    <description>Life Chances Fund - Full Application - 1.0</description>
    <label>Form LCF Full Application 1.0</label>
    <nameField>
        <displayFormat>FAP-{00000}</displayFormat>
        <label>Form ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Form LCF Full Application 1.0</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Form LCF Full Application 1.0</relationshipLabel>
        <relationshipName>Form_LCF_Full_Application_1_0</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ov_services_start_date__c</fullName>
        <inlineHelpText>When would you like your project to start delivering services?</inlineHelpText>
        <label>OV - Services Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>si_themes__c</fullName>
        <inlineHelpText>What is the theme of your project?</inlineHelpText>
        <label>SI - Themes</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Children's services</fullName>
                </value>
                <value>
                    <fullName>Drug and alcohol dependency</fullName>
                </value>
                <value>
                    <fullName>Young people</fullName>
                </value>
                <value>
                    <fullName>Healthy lives</fullName>
                </value>
                <value>
                    <fullName>Older people's services</fullName>
                </value>
                <value>
                    <fullName>Early years</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/default/objects/SIB_Information__c/SIB_Information__c.object-meta.xml
<CustomObject>
    <description>Informative text relating to SIB Applications</description>
    <label>SIB Reference Information</label>
    <nameField>
        <label>SIB Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SIB Reference</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SIB_Section_Text__c/SIB_Section_Text__c.object-meta.xml
<CustomObject>
    <description>Rich text used in Section Titles in SIB Forms</description>
    <label>SIB Section Text</label>
    <nameField>
        <label>Text ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SIB Section Text</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SIB_Section_Text__c/fields/Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_Name__c</fullName>
    <description>API Name of Form Object</description>
    <inlineHelpText>API Name of Form Object</inlineHelpText>
    <label>Object Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SIB_Object_Name</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SIB_Section_Text__c/fields/SIB_Reference__c.field-meta.xml
<CustomField>
    <fullName>SIB_Reference__c</fullName>
    <description>SIB Reference Information parent record</description>
    <inlineHelpText>SIB Reference Information parent record</inlineHelpText>
    <label>SIB Reference</label>
    <referenceTo>SIB_Information__c</referenceTo>
    <relationshipLabel>Section Text</relationshipLabel>
    <relationshipName>Section_Text</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SIB_Section_Text__c/fields/Text__c.field-meta.xml
<CustomField>
    <fullName>Text__c</fullName>
    <description>Plain or rich text used in section summaries, page titles etc in SIB Forms</description>
    <inlineHelpText>Plain or rich text used in section summaries, page titles etc in SIB Forms</inlineHelpText>
    <label>Text</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/globalValueSets/SIB_Object_Name.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Application__c</fullName>
    </customValue>
    <customValue>
        <fullName>Form_LCF_EOI_1__c</fullName>
    </customValue>
    <customValue>
        <fullName>Form_LCF_Full_App_1__c</fullName>
    </customValue>
    <customValue>
        <fullName>Form_LCF_Outcome_1__c</fullName>
    </customValue>
    <customValue>
        <fullName>Form_LCF_Commissioner_1__c</fullName>
    </customValue>
    <customValue>
        <fullName>Form_LCF_Previous_App_1__c</fullName>
    </customValue>
    <customValue>
        <fullName>Form_LCF_Setup_1__c</fullName>
    </customValue>
    <customValue>
        <fullName>Form_LCF_Disengagement_1__c</fullName>
    </customValue>
    <customValue>
        <fullName>Form_LCF_Setup_Investor_1__c</fullName>
    </customValue>
    <customValue>
        <fullName>Form_LCF_Outcome_Payment_1__c</fullName>
    </customValue>
    <customValue>
        <fullName>LCF_Grant__c</fullName>
    </customValue>
    <customValue>
        <fullName>Form_LCF_Grant_Baseline_1__c</fullName>
    </customValue>
    <customValue>
        <fullName>Form_LCF_Grant_Profile_1__c</fullName>
    </customValue>
    <customValue>
        <fullName>Form_LCF_Grant_Outcome_1__c</fullName>
    </customValue>
    <customValue>
        <fullName>Form_LCF_Grant_Annual_Block_1__c</fullName>
    </customValue>
    <customValue>
        <fullName>Form_LCF_Grant_End_1__c</fullName>
    </customValue>
    <customValue>
        <fullName>Form_LCF_Grant_Investor_1</fullName>
    </customValue>
    <customValue>
        <fullName>Form_LCF_Grant_Term_1</fullName>
    </customValue>
    <customValue>
        <fullName>Form_LCF_Grant_Achievement_1__c</fullName>
    </customValue>
    <customValue>
        <fullName>Form_LCF_Outcome_Achievement_1__c</fullName>
    </customValue>
    <customValue>
        <fullName>Form_LCF_Payment_Trigger_1__c</fullName>
    </customValue>
    <customValue>
        <fullName>Form_LCF_Outcome_Metric__c</fullName>
    </customValue>
    <customValue>
        <fullName>Form_LCF_Grant_Payment_Profile_1__c</fullName>
    </customValue>
    <customValue>
        <fullName>Form_LCF_Grant_Payment_History_1__c</fullName>
    </customValue>
    <customValue>
        <fullName>Form_LCF_Grant_Annual_1__c</fullName>
        <isActive>false</isActive>
        <label>Form_LCF_Grant_Annual_1__c</label>
    </customValue>
    <description>Object names of SIB Forms</description>
    <masterLabel>SIB Object Name</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/StartControllerTest.cls
/* _______________________________________________________________________________________________________________
   Name:		StartControllerTest.cls
   Description: Test Class for StartController
					
   Date         Version Author          	Summary of Changes 
   ___________  _______ __________________	______________________________________________________________________
   Jan 2018     1.0     Michael Witchalls	Initial Release 
__________________________________________________________________________________________________________________ */        
@isTest
private class StartControllerTest { 
	private static final String RECORDTYPE = 'Full Application';
	private static final String THEME1 = 'Children\'s services';
	private static final String THEME2 = 'Healthy lives';
	private static final String STAGE = 'Full Application';
	private static final String DRAFT = 'Draft';
	
	@testSetup static void setup() {
		// Add section text
		SIB_Information__c info = new SIB_Information__c(Name = 'Life Chances Fund');
		insert info;
		SIB_Section_Text__c text = new SIB_Section_Text__c(
			SIB_Reference__c = info.Id,
			Name = 'lcf_full_app_overview_1',
			Object_Name__c = 'Form_LCF_Full_App_1__c',
			Text__c = 'Section Text'
		);
    	insert text;
    	
		// Create an Application
		Application__c a = new Application__c(
			RecordTypeId = Schema.SObjectType.Application__c.getRecordTypeInfosByName().get(RECORDTYPE).getRecordTypeId(),
			application_theme__c = THEME1,
			Application_Stage__c = STAGE,
			Full_Application_Status__c = DRAFT
		);
		insert a;
		// Create a Full Application Form
		Form_LCF_Full_App_1__c f = new Form_LCF_Full_App_1__c(
			application__c = a.Id,
			ov_services_start_date__c = System.Today(),
			si_themes__c = THEME1+';'+THEME2
		);
		insert f;
	}    
	
    @isTest static void testit() {
    	// Start?form=lcf_full_app_1&section=lcf_full_app_overview_1&app=APP-01118
    	Application__c a = [SELECT Id, Name FROM Application__c LIMIT 1];
		
        PageReference pageRef = Page.Start;
        Test.setCurrentPage(pageRef);     
        ApexPages.currentPage().getParameters().put('app', a.Name);      
        ApexPages.currentPage().getParameters().put('form', 'lcf_full_app_1');      
        ApexPages.currentPage().getParameters().put('section', 'lcf_full_app_overview_1');      
         
		Test.startTest();
		StartController con1 = new StartController();
		con1.start();
		con1.summaryPage();
     	
     	Test.stopTest();
        system.assertEquals(a.Name, con1.application.get('Name'));
    }  
    
    
}