force-app/main/default/mdapioutput/objects/Application__c.object
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{00000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Application_Stage__c</fullName>
        <label>Application Stage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Expression of Interest</fullName>
                    <default>true</default>
                    <label>Expression of Interest</label>
                </value>
                <value>
                    <fullName>Full Application</fullName>
                </value>
                <value>
                    <fullName>Live Project</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>application_theme__c</fullName>
        <label>Application Theme</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Children's services</fullName>
                </value>
                <value>
                    <fullName>Drug and alcohol dependency</fullName>
                </value>
                <value>
                    <fullName>Early years</fullName>
                </value>
                <value>
                    <fullName>Healthy lives</fullName>
                </value>
                <value>
                    <fullName>Older people's services</fullName>
                </value>
                <value>
                    <fullName>Young people</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Full_Application_Status__c</fullName>
        <label>Full Application Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Under review (In progress)</fullName>
                </value>
                <value>
                    <fullName>Ready for Approval</fullName>
                </value>
                <value>
                    <fullName>Successful</fullName>
                </value>
                <value>
                    <fullName>Unsuccessful</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/default/objects/Application__c/fields/Full_App_Primary_Commissioner__c.field-meta.xml
<CustomField>
    <fullName>Full_App_Primary_Commissioner__c</fullName>
    <description>Organisation of Full Application Primary Commissioner</description>
    <inlineHelpText>Organisation of Full Application Primary Commissioner</inlineHelpText>
    <label>Full App Primary Commissioner</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Full_App_Primary_Commissioner_Region__c.field-meta.xml
<CustomField>
    <fullName>Full_App_Primary_Commissioner_Region__c</fullName>
    <description>Region of primary commissioner organisation</description>
    <inlineHelpText>Region of primary commissioner organisation</inlineHelpText>
    <label>Full App Primary Commissioner Region</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Organisation_Region</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/mdapioutput/objects/Form_LCF_Commissioner_1__c.object
<CustomObject>
    <description>Life Chances Fund - Full Application - Commissioner - 1.0</description>
    <label>Form LCF Commissioner 1.0</label>
    <nameField>
        <displayFormat>COM-{00000}</displayFormat>
        <label>Commissioner ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Form LCF Commissioner 1.0</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Form LCF Commissioner 1.0</relationshipLabel>
        <relationshipName>commissioners</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>full_application__c</fullName>
        <label>Form LCF Full Application 1.0</label>
        <referenceTo>Form_LCF_Full_App_1__c</referenceTo>
        <relationshipLabel>Form LCF Commissioner 1.0</relationshipLabel>
        <relationshipName>full_application_commissioners</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

force-app/main/default/objects/Form_LCF_Commissioner_1__c/fields/eoi__c.field-meta.xml
<CustomField>
    <fullName>eoi__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Form LCF EOI 1.0</label>
    <referenceTo>Form_LCF_EOI_1__c</referenceTo>
    <relationshipName>eoi_commissioners</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Form_LCF_Commissioner_1__c/fields/primary__c.field-meta.xml
<CustomField>
    <fullName>primary__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Primary commissioner</inlineHelpText>
    <label>Primary</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Form_LCF_Commissioner_1__c/fields/st_organisation_name__c.field-meta.xml
<CustomField>
    <fullName>st_organisation_name__c</fullName>
    <inlineHelpText>Name of organisation</inlineHelpText>
    <label>ST - Organisation Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Form_LCF_Commissioner_1__c/fields/st_organisation_region__c.field-meta.xml
<CustomField>
    <fullName>st_organisation_region__c</fullName>
    <description>Please select either &#39;England wide&#39; or one or more regions of England</description>
    <inlineHelpText>What region is the organisation in?</inlineHelpText>
    <label>ST - Organisation Region</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Organisation_Region</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Form_LCF_Commissioner_1__c/recordTypes/EOI.recordType-meta.xml
<RecordType>
    <fullName>EOI</fullName>
    <active>true</active>
    <description>Expression of Interest Commissioner Record Type</description>
    <label>EOI</label>
</RecordType>

force-app/main/default/objects/Form_LCF_Commissioner_1__c/recordTypes/Setup.recordType-meta.xml
<RecordType>
    <fullName>Setup</fullName>
    <active>true</active>
    <description>Stakeholder record used in Full Award Setup form</description>
    <label>Setup</label>
</RecordType>

force-app/main/default/objects/Form_LCF_EOI_1__c/Form_LCF_EOI_1__c.object-meta.xml
<CustomObject>
    <description>LCF Expression of Interest Form - 1.0</description>
    <label>Form LCF EOI 1.0</label>
    <nameField>
        <displayFormat>EOI-{00000}</displayFormat>
        <label>Form ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Form LCF EOI</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Form_LCF_EOI_1__c/fields/application__c.field-meta.xml
<CustomField>
    <fullName>application__c</fullName>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Form LCF EOI 1.0</relationshipLabel>
    <relationshipName>Form_LCF_EOI_1_0</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/mdapioutput/objects/Form_LCF_Full_App_1__c.object
<CustomObject>
    <description>Life Chances Fund - Full Application - 1.0</description>
    <label>Form LCF Full Application 1.0</label>
    <nameField>
        <displayFormat>FAP-{00000}</displayFormat>
        <label>Form ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Form LCF Full Application 1.0</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Form LCF Full Application 1.0</relationshipLabel>
        <relationshipName>Form_LCF_Full_Application_1_0</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ov_services_start_date__c</fullName>
        <inlineHelpText>When would you like your project to start delivering services?</inlineHelpText>
        <label>OV - Services Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>si_themes__c</fullName>
        <inlineHelpText>What is the theme of your project?</inlineHelpText>
        <label>SI - Themes</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Children's services</fullName>
                </value>
                <value>
                    <fullName>Drug and alcohol dependency</fullName>
                </value>
                <value>
                    <fullName>Young people</fullName>
                </value>
                <value>
                    <fullName>Healthy lives</fullName>
                </value>
                <value>
                    <fullName>Older people's services</fullName>
                </value>
                <value>
                    <fullName>Early years</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/default/globalValueSets/Organisation_Region.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>England wide</fullName>
    </customValue>
    <customValue>
        <fullName>London</fullName>
    </customValue>
    <customValue>
        <fullName>South East</fullName>
    </customValue>
    <customValue>
        <fullName>South West</fullName>
    </customValue>
    <customValue>
        <fullName>East of England</fullName>
    </customValue>
    <customValue>
        <fullName>East Midlands</fullName>
    </customValue>
    <customValue>
        <fullName>West Midlands</fullName>
    </customValue>
    <customValue>
        <fullName>Yorkshire and the Humber</fullName>
    </customValue>
    <customValue>
        <fullName>North West</fullName>
    </customValue>
    <customValue>
        <fullName>North East</fullName>
    </customValue>
    <description>Geography of Organisation (multi-select)</description>
    <masterLabel>Organisation Region</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/LCFCommissionerTriggerHandlerTest.cls
/* _______________________________________________________________________________________________________________
   Name:		LCFCommissionerTriggerHandlerTest.cls
   Description: Test Class for LCFCommissionerTriggerHandler
					
   Date         Version Author          	Summary of Changes 
   ___________  _______ __________________	______________________________________________________________________
   Mar 2018     1.0     Michael Witchalls	Initial Release 
__________________________________________________________________________________________________________________ */        
@isTest
private class LCFCommissionerTriggerHandlerTest { 
	private static final String RECORDTYPE = 'Full Application';
	private static final String THEME1 = 'Children\'s services';
	private static final String THEME2 = 'Healthy lives';
	private static final String STAGE = 'Full Application';
	private static final String DRAFT = 'Draft';
	
	@testSetup static void setup() {   	
		// Create an Application
		Application__c a = new Application__c(
			RecordTypeId = Schema.SObjectType.Application__c.getRecordTypeInfosByName().get(RECORDTYPE).getRecordTypeId(),
			application_theme__c = THEME1,
			Application_Stage__c = STAGE,
			Full_Application_Status__c = DRAFT
		);
		insert a;
		// Create a Full Application Form
		Form_LCF_Full_App_1__c f = new Form_LCF_Full_App_1__c(
			application__c = a.Id,
			ov_services_start_date__c = System.Today(),
			si_themes__c = THEME1+';'+THEME2
		);
		insert f;
		// Create an EOI Form
		Form_LCF_EOI_1__c e = new Form_LCF_EOI_1__c(
			application__c = a.Id
		);
		insert e;
	}    
	
    @isTest static void testit() {
    	Form_LCF_Full_App_1__c f = [SELECT Id, application__c FROM Form_LCF_Full_App_1__c LIMIT 1];
    	Form_LCF_EOI_1__c e = [SELECT Id, application__c FROM Form_LCF_EOI_1__c LIMIT 1];
    	
    	Test.startTest();
		// Create a Commissioner
		Form_LCF_Commissioner_1__c c = new Form_LCF_Commissioner_1__c(
			application__c = f.application__c,
			full_application__c = f.Id,
			eoi__c = e.Id,
			st_organisation_name__c = 'Test Organisation',
			st_organisation_region__c = 'London',
			primary__c = true
		);
		insert c;
		c.st_organisation_region__c = 'South East'; 
		update c;
		Test.stopTest();
		
		Application__c a = [SELECT Id, Full_App_Primary_Commissioner__c, Full_App_Primary_Commissioner_Region__c FROM Application__c LIMIT 1];
		system.assertEquals('South East', a.Full_App_Primary_Commissioner_Region__c);
    }  
    
}