force-app/main/default/mdapioutput/objects/Application__c.object
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{00000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Application_Stage__c</fullName>
        <label>Application Stage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Expression of Interest</fullName>
                    <default>true</default>
                    <label>Expression of Interest</label>
                </value>
                <value>
                    <fullName>Full Application</fullName>
                </value>
                <value>
                    <fullName>Live Project</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Application</relationshipLabel>
        <relationshipName>Application</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Dev_Form_External_Status__c</fullName>
        <formula>IF(
   OR(
      TEXT(Development_Form_Status__c) = "Under Review", 
      TEXT(Development_Form_Status__c) = "Under Review (In Progress)", 
      TEXT(Development_Form_Status__c) = "Ready for Approval"
   ), "Submitted", TEXT(Development_Form_Status__c)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Dev Form External Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Eligible_for_Full_Application__c</fullName>
        <formula>IF(
AND(
 Dev_Form_External_Status__c == 'Successful',
 EOI_External_Status__c == 'Successful',
 Identity_Check_External_Status__c == 'Successful'
), TRUE, FALSE
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Eligible for Full Application</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EOI_External_Status__c</fullName>
        <formula>IF(
   OR(
      TEXT(Status__c) = "Under Review", 
      TEXT(Status__c) = "Under Review (In Progress)", 
      TEXT(Status__c) = "Ready for Approval"
   ), "Submitted", TEXT(Status__c)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>EOI External Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Full_Application_External_Status__c</fullName>
        <formula>IF(
   OR(
      TEXT(Full_Application_Status__c) = "Under Review", 
      TEXT(Full_Application_Status__c) = "Under Review (In Progress)", 
      TEXT(Full_Application_Status__c) = "Ready for Approval"
   ), "Submitted", TEXT(Full_Application_Status__c)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Full Application External Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Identity_Check_External_Status__c</fullName>
        <formula>IF( 
OR( 
TEXT( Identity_Check_Status__c ) = "Under Review", 
TEXT(Identity_Check_Status__c) = "Under Review (In Progress)", 
TEXT(Identity_Check_Status__c) = "Ready for Approval" 
), "Submitted", TEXT(Identity_Check_Status__c) 
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Financial health External Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>EOI Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Under review (In progress)</fullName>
                </value>
                <value>
                    <fullName>Ready for Approval</fullName>
                </value>
                <value>
                    <fullName>Successful</fullName>
                </value>
                <value>
                    <fullName>Unsuccessful</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Theme__c</fullName>
        <formula>IF(NOT(ISBLANK(TEXT(application_theme__c))),
TEXT(application_theme__c),
Application_Window_Template__r.Application_Window__r.Theme__r.Name
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Theme</label>
        <type>Text</type>
    </fields>
</CustomObject>

force-app/main/default/objects/Application__c/fields/Eligible_for_NEW_EOI_Form__c.field-meta.xml
<CustomField>
    <fullName>Eligible_for_NEW_EOI_Form__c</fullName>
    <formula>$User.Eligible_for_NEW_EOI_Form__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Eligible for NEW EOI Form</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/mdapioutput/objects/Theme__c.object
<CustomObject>
    <description>The category under which projects are classified. Applicants interest is initially captured against a theme</description>
    <label>Theme</label>
    <nameField>
        <label>Theme Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Themes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/mdapioutput/objects/User.object
<CustomObject>
    <fields>
        <fullName>Eligible_for_Full_Application__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Community user is eligible for the Full Application Form</inlineHelpText>
        <label>Eligible for Full Application</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

force-app/main/default/objects/User/fields/Eligible_for_Full_Award_Setup__c.field-meta.xml
<CustomField>
    <fullName>Eligible_for_Full_Award_Setup__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Eligible for Full Award Setup</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/Eligible_for_LCF_Grant__c.field-meta.xml
<CustomField>
    <fullName>Eligible_for_LCF_Grant__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Determines whether the user can access the LCF Grants page</description>
    <inlineHelpText>Determines whether the user can access the LCF Grants page</inlineHelpText>
    <label>Eligible for LCF Grant</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/Eligible_for_NEW_EOI_Form__c.field-meta.xml
<CustomField>
    <fullName>Eligible_for_NEW_EOI_Form__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Eligible for NEW EOI Form</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/SIB_ApplicationListController.cls
public with sharing class SIB_ApplicationListController {
	/*
		M.Witchalls Jan 2018: Divert to new Applications page if eligible for Full Application
	*/
	private Boolean eligible = true;
	private Boolean eligibleForGrant = false;
	private ID contactId;
	
	public SIB_ApplicationListController() {
		User u = [SELECT ContactId, Eligible_for_Full_Application__c, Eligible_for_Full_Award_Setup__c, Eligible_for_NEW_EOI_Form__c, Eligible_for_LCF_Grant__c FROM User WHERE Id = :UserInfo.getUserId()];
		eligible = u.Eligible_for_Full_Application__c;
		eligibleForGrant = u.Eligible_for_LCF_Grant__c;
		contactId = u.ContactId;
	}
	
    //As with all the pages where we require a user to be logged in, we check here if the user is logged in, else return the homepage
    public PageReference checkLoggedInStatus(){
    	PageReference nextPage = SIB_Utilities.checkLoggedInStatus();
    	if (nextPage == Page.SIB_Login || !eligible) {
    		return nextPage;
    	} else if (eligibleForGrant) {
    		return Page.LCFGrants;
    	} else {
    		return Page.Applications;
    	}
    }
    /*
        This method returns all applications. Because of how security is set up and the "with sharing" setting, 
        we dont need to worry about hiding other applications from other users.
    */
    public List<Application__c> getApplications(){
    	if (contactId != null) {// Customer user
	    	return [
	            SELECT Id, Status__c, Theme__c, Application_Stage__c, Name, 
	            EOI_External_Status__c, Dev_Form_External_Status__c, Full_Application_External_Status__c, Identity_Check_External_Status__c
	            FROM Application__c
	            WHERE Contact__c = :contactId
	            ORDER BY Theme__c
	    	];
    	} else {// internal user (testing on limited data)
	        return [
	            SELECT Id, Status__c, Theme__c, Application_Stage__c, Name, 
	            EOI_External_Status__c, Dev_Form_External_Status__c, Full_Application_External_Status__c, Identity_Check_External_Status__c
	            FROM Application__c
	            ORDER BY Theme__c
	        ];
    	}
    }
}