force-app/main/default/mdapioutput/objects/Footer_Link__mdt.object
<CustomObject>
    <description>This custom setting will contain the href, target, label to display on the footer section on the SIB_Template page.</description>
    <label>Footer Link</label>
    <pluralLabel>Footer Links</pluralLabel>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field will define whether or not the link should display on the template page.</description>
        <inlineHelpText>This field will define whether or not the link should display on the template page.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Target__c</fullName>
        <description>This field will house the target you wish to display in the "target" on the &lt;a> tag. Please note: values from the following link are valid markup:

https://www.w3schools.com/tags/att_a_target.asp</description>
        <inlineHelpText>This field will house the target you wish to display in the "target" on the &lt;a> tag. Please note: values from the following link are valid markup:

https://www.w3schools.com/tags/att_a_target.asp</inlineHelpText>
        <label>Target</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>URL__c</fullName>
        <description>This field will house the URL you wish to display in the "href" tag on the &lt;a> tag.</description>
        <inlineHelpText>This field will house the URL you wish to display in the "href" tag on the &lt;a> tag.</inlineHelpText>
        <label>URL</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
</CustomObject>

force-app/main/default/mdapioutput/classes/SIB_TemplateController.cls
public with sharing class SIB_TemplateController {
	public List<Footer_Link__mdt> footerLinks{get;set;}

	/* 
		This method is used to set up the footer links on the visualforce page. These are stored in a custom metadata type.
		The only variable checked here is the checkbox "Active__c", to define whether these should show up. This is loaded on
		page load, as there will only need to be done the first time the template is loaded.
	*/
	public SIB_TemplateController(){
		footerLinks = [
			SELECT Label, URL__c, Target__c
			FROM Footer_Link__mdt
			WHERE Active__c = true
		];
	}
}