force-app/main/default/mdapioutput/objects/Footer_Link__mdt.object
<CustomObject>
    <description>This custom setting will contain the href, target, label to display on the footer section on the SIB_Template page.</description>
    <label>Footer Link</label>
    <pluralLabel>Footer Links</pluralLabel>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field will define whether or not the link should display on the template page.</description>
        <inlineHelpText>This field will define whether or not the link should display on the template page.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Target__c</fullName>
        <description>This field will house the target you wish to display in the "target" on the &lt;a> tag. Please note: values from the following link are valid markup:

https://www.w3schools.com/tags/att_a_target.asp</description>
        <inlineHelpText>This field will house the target you wish to display in the "target" on the &lt;a> tag. Please note: values from the following link are valid markup:

https://www.w3schools.com/tags/att_a_target.asp</inlineHelpText>
        <label>Target</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>URL__c</fullName>
        <description>This field will house the URL you wish to display in the "href" tag on the &lt;a> tag.</description>
        <inlineHelpText>This field will house the URL you wish to display in the "href" tag on the &lt;a> tag.</inlineHelpText>
        <label>URL</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
</CustomObject>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Projects, which can also be called Social Impact Bonds, are separate entities, which have a social improvement aim. The difference between these and grants or loans are the way they are structured, where the funding comes in avg 20% from gov funding and 80% from a private investor and the payment from gov is only given upon agreed specific outcomes being achieved</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Data_Protection_Text__c.field-meta.xml
<CustomField>
    <fullName>Data_Protection_Text__c</fullName>
    <inlineHelpText>Text used by COF_DP Visualforce page</inlineHelpText>
    <label>Data Protection Text</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Declaration_Text__c.field-meta.xml
<CustomField>
    <fullName>Declaration_Text__c</fullName>
    <inlineHelpText>Text that appears on the Start Page of the Declaration section</inlineHelpText>
    <label>Declaration Text</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Freedom_of_Information_Act_Text__c.field-meta.xml
<CustomField>
    <fullName>Freedom_of_Information_Act_Text__c</fullName>
    <inlineHelpText>Text used by COF_FOI Visualforce page</inlineHelpText>
    <label>Freedom of Information Act Text</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/classes/SIB_TemplateController.cls
public with sharing class SIB_TemplateController {
	private static final String LCF = 'Life Chances Fund';
	public List<Footer_Link__mdt> footerLinks{get;set;}
	public Project__c project {get;set;}

	/* 
		This method is used to set up the footer links on the visualforce page. These are stored in a custom metadata type.
		The only variable checked here is the checkbox "Active__c", to define whether these should show up. This is loaded on
		page load, as there will only need to be done the first time the template is loaded.
	*/
	public SIB_TemplateController(){
		footerLinks = [
			SELECT Label, URL__c, Target__c
			FROM Footer_Link__mdt
			WHERE Active__c = true
		];
		
		List<Project__c> projectList = [
			SELECT 
				Data_Protection_Text__c, Freedom_of_Information_Act_Text__c, Declaration_Text__c 
			FROM 
				Project__c 
			WHERE
				Name = :LCF
		];
		if (projectList.size() > 0) project = projectList[0];
	}
}