force-app/main/default/objects/Form_LCF_Grant_Outcome_1__c/Form_LCF_Grant_Outcome_1__c.object-meta.xml
<CustomObject>
    <description>Life Chances Fund Grant Management - Outcome - 1.0</description>
    <label>Form LCF Grant Outcome 1.0</label>
    <nameField>
        <displayFormat>GOU-{00000}</displayFormat>
        <label>Outcome ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LCF Grant Outcomes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Form_LCF_Grant_Outcome_1__c/fields/ou_outcome_metrics__c.field-meta.xml
<CustomField>
    <fullName>ou_outcome_metrics__c</fullName>
    <inlineHelpText>Agreed outcome metrics - up to 3</inlineHelpText>
    <label>OU - Outcome Metrics</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Form_LCF_Outcome_Metric_1__c/Form_LCF_Outcome_Metric_1__c.object-meta.xml
<CustomObject>
    <description>Life Chances Fund Grant Management - Outcome Metric - 1.0</description>
    <label>Form LCF Outcome Metric 1.0</label>
    <nameField>
        <displayFormat>MET-{00000}</displayFormat>
        <label>Metric ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LCF Grant Outcome Metrics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Form_LCF_Outcome_Metric_1__c/fields/grant_outcome__c.field-meta.xml
<CustomField>
    <fullName>grant_outcome__c</fullName>
    <label>Form LCF Grant Outcome 1.0</label>
    <referenceTo>Form_LCF_Grant_Outcome_1__c</referenceTo>
    <relationshipLabel>Form LCF Outcome Metrics</relationshipLabel>
    <relationshipName>outcome_metrics</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Form_LCF_Outcome_Metric_1__c/fields/om_description__c.field-meta.xml
<CustomField>
    <fullName>om_description__c</fullName>
    <inlineHelpText>Description</inlineHelpText>
    <label>OM - Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Form_LCF_Outcome_Metric_1__c/fields/om_individual_cohort__c.field-meta.xml
<CustomField>
    <fullName>om_individual_cohort__c</fullName>
    <inlineHelpText>Is the outcome metric measured at individual or at cohort level?</inlineHelpText>
    <label>OM - Indvidual/Cohort</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Individual_Cohort</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Individual_Cohort.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Individual</fullName>
    </customValue>
    <customValue>
        <fullName>Cohort</fullName>
    </customValue>
    <description>Type of Outcome Measure or Metric</description>
    <masterLabel>Individual/Cohort</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/COF_OutcomeMetricTriggerHandler.cls
/* _______________________________________________________________________________________________________________
   Name:		COF_OutcomeMetricTriggerHandler.cls
   Description: Trigger actions on LCF Outcome Metric records
					
   Date         Version Author          	Summary of Changes 
   ___________  _______ __________________	______________________________________________________________________
   May 2018		1.0     Michael Witchalls	Initial Release 
__________________________________________________________________________________________________________________ */
public class COF_OutcomeMetricTriggerHandler {
    	
	/*
	 *	Purpose: On insert/update/delete/undelete copy all records to the parent Grant Outcome record
	 *	History: 
	 *		May 2018: Michael Witchalls: Initial Release 
	 *
	 */
	public void copyRecordsToParents(List<Form_LCF_Outcome_Metric_1__c> items) {
		Set<ID> outcomeIdSet = new Set<ID>();
		for (Form_LCF_Outcome_Metric_1__c item: items) {
			outcomeIdSet.add(item.grant_outcome__c);
		}
		Map<ID, Form_LCF_Grant_Outcome_1__c> outcomeMap = new Map<ID, Form_LCF_Grant_Outcome_1__c>([
			SELECT 
				Id, (SELECT om_description__c, om_individual_cohort__c FROM outcome_metrics__r WHERE isDeleted = false)
			FROM	
				Form_LCF_Grant_Outcome_1__c
			WHERE
				Id IN :outcomeIdSet
		]);
		
		List<Form_LCF_Grant_Outcome_1__c> outcomeList = new List<Form_LCF_Grant_Outcome_1__c>();
		for (ID outcomeId: outcomeMap.keySet()) {
			String outcomeMetricString = '<table><tr><th><b>Description</b></th><th><b>Individual/Cohort</b></th><tr>';
			for (Form_LCF_Outcome_Metric_1__c item: outcomeMap.get(outcomeId).outcome_metrics__r) {
				outcomeMetricString += '<tr><td>'+item.om_description__c+'</td><td>'+item.om_individual_cohort__c+'</td></tr>';
			}
			outcomeMetricString += '</table>';
			outcomeList.add(
				new Form_LCF_Grant_Outcome_1__c(
					Id = outcomeId,
					ou_outcome_metrics__c = outcomeMetricString					
				)
			);
			system.debug('@@@@outcomeList: '+outcomeList);
		}
		update outcomeList;
	}
    
}